### ISSUE TITLE
Unity Admob Ads not showing in all devices

### ISSUE THREAD

**Issue by eanjo7** [googleads/googleads-mobile-unity#1031]
First I try to install my app to my one plus 7 pro.
the ads works perfectly fine, restart the game ads still shows up.
same in my lenovo.

But when i install it to my samsung s7 edge, and samsung s3
The ads shows up at start, and the second time I called it, it never appears.
then I restarted the app. and still no ads showing. maybe I restated it 3-4 times then ads shows up again. this thing is random and cant be detected.

Im struggling for this ad a whole week!! 
If not for googelplay 64bit requirement I will never update this!.

all my ads is working unityads, applovin, vungle.
this one made by google doesnt work consistently. I tried so many different versions of plugin!.

I HOPE GOOGLE WILL FIND A NEW ADMOB TEAM. that can make their work output better and less headache for developers!

**Comment by UragayalaDeepika** [comment]
@eanjo7 Can you please capture the device logs and share it with us so that we can take a look at the error code that you are receiving when you failed to load an ad on those devices? This kind of issues usually reported to us will turn out as device specific issues and  I would suggest you to make sure that you don't have any Ad Blocker or custom ROM installed on the device where the Ads failed to load. Also, could you confirm if that device is connected in the same network when you were testing? If not, you may also check if there are any Ad Filter/Blocker in the network your device is connected where the Ads failed to load.

**Comment by willmeet** [comment]
[That issue is clearly shown here how to solve admob failed to load ads](http://www.technologymanias.com/2020/10/admob-ads-failed-to-load-ads-solve-this.html)
