### ISSUE TITLE
CRASH WITHOUT SHOWING ANY LOG

### ISSUE THREAD

**Issue by muafakul** [googleads/googleads-mobile-unity#1033]
JUST IMPLEMENT ANYTHING AND CRASH SUPER FAST

**Comment by UragayalaDeepika** [comment]
@muafakul Can you please elaborate your issue so that we can assist you? Can you add the details about your implementation?

**Comment by bencehari** [comment]
I had the same. When I started the application it crashed immediatelly without any logs with Unity and Ads filter.
When I filtered with adb logcat *:E (only errors) I found that the problem was with the appId (I accidentally copied into Unity a productId instead of appId).
After that everything started working.

Hope this helps someone

**Comment by stowy** [comment]
Thanks @bencehari for adding that.
