### ISSUE TITLE
Staging temp cry error dont know why

### ISSUE THREAD

**Issue by stickylabdev** [googleads/googleads-mobile-unity#1034]
![image](https://user-images.githubusercontent.com/13078369/66476841-c4ed0980-eac0-11e9-8765-4a8867742b0c.png)

**Comment by UragayalaDeepika** [comment]
@muafakul It looks like a missing library and might be due to your Android SDK path missing in GMS framework. Make sure that you are following the guidelines as mentioned here and integrate with our [sample app](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld) and then see if you are still able to reproduce this issue. Also, can you check via the SDK Manager via Android Studio and make sure that Play Services is updated and try again?
