### ISSUE TITLE
All Callbacks of RewardedAd are not running in main thread of unity

### ISSUE THREAD

**Issue by dqh147258** [googleads/googleads-mobile-unity#1059]
I read the source code of RewardedAd found that all callbacks of RewardedAd are not running on the main thread of unity. It may cause many problem, please fix it soon. And I found that the sdk provide a class which name is "MobileAdsEventExecutor" could resolve the problem, but the class has not been used in the sdk.

**Comment by mobile94ever** [comment]
Same issue. RewardedAds are giving a missing reference exception related to UnityEvent callback

**Comment by stowy** [comment]
In terms of main thread this is the case and has been the case for all formats for some time. We can't use the MobileAdsEventExecutor because it won't run while the ad activity is showing.

Are you facing the same problem with other formats?

@mobile94ever can you please share an example of what callback is raising an exception - a stack trace would be a good starting point.

**Comment by dqh147258** [comment]
The UnityEngine not allow accessing it not in main thread , if we access UnityEngine not in main thread the application may crash.

Most of the time we don't need handling event while unity is stopped , you could let the events run before or after the ad activity is showing.

Even if you don't , I think you should remind users that all callbacks is not running in main thread in developer guide.

**Comment by BenDevelopment** [comment]
Is there a way to bypass this problem?
I'm trying to run Unity code (a function to start a new game), after the intertitial ad has been closed. But it doesn't works because the OnAdClosed is not running on the main Unity thread, and my NewGame method need to instanciate new GameObjects (and it cannot be done outside the main Unity thread).

**Comment by dqh147258** [comment]
@BenDevelopment you can just use the "MobileAdsEventExecutor.cs" to avoid the problem.

**Comment by BenDevelopment** [comment]
It works like a charm, thank you @dqh147258 !
