### ISSUE TITLE
Mediation Test Suite 1.2.2 crash android

### ISSUE THREAD

**Issue by Thaina** [googleads/googleads-mobile-unity#1121]
Build android with latest `Google Mobile Ads Unity Plugin v4.1.0` with `Vungle` `UnityAd` `ChartBoost` and `AdColony` mediation. When opening the test suite, it seem normal until I try to go into any mediation to load ad, it crash

logcat is like this

```
12-27 17:31:03.346  6895  6895 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.MyCompany.MyApp/com.google.android.ads.mediationtestsuite.activities.NetworkDetailActivity}: java.lang.IllegalStateException: MobileAds.initialize() must be called prior to getting version string.
12-27 17:31:03.346  6895  6895 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2928)
12-27 17:31:03.346  6895  6895 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3063)

....
....
....
....

12-27 17:31:04.136  7201  7201 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.MyCompany.MyApp/com.google.android.ads.mediationtestsuite.activities.HomeActivity}: java.lang.NullPointerException: Attempt to invoke direct method 'com.google.android.ads.mediationtestsuite.dataobjects.ProductTheme com.google.android.ads.mediationtestsuite.utils.logging.TestSuiteState.getProductThemeInstance()' on a null object reference
12-27 17:31:04.136  7201  7201 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2928)
12-27 17:31:04.136  7201  7201 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3063)
12-27 17:31:04.136  7201  7201 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
12-27 17:31:04.136  7201  7201 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
12-27 17:31:04.136  7201  7201 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
12-27 17:31:04.136  7201  7201 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823)
```

Using `1.0.0` work fine except Vungle cannot be tested ( same as #859 )

**Comment by dnyanesh11118** [comment]
Good

**Comment by stowy** [comment]
This may be happening because you are not initializing the Mobile Ads SDK before launching the test suite.  The [AdMob Unity documentation](https://developers.google.com/admob/unity/start#initialize_mobileads) specifies that you should initialize the SDK on app launch.

Also, are you including the AdMob App ID in your application manifest, as per [these docs](https://developers.google.com/admob/unity/start#set_your_admob_app_id)?

**Comment by Thaina** [comment]
@stowy Did anything become difference between `1.0.0` and `1.2.2` ? In 1.0.0 I don't need to do initial bits

**Comment by stowy** [comment]
Yes quite a bit has changed, see these Android release notes:

https://groups.google.com/forum/#!searchin/google-admob-ads-sdk/mediation$20test$20suite%7Csort:date/google-admob-ads-sdk/cFrbpA4Rgwk/UqAWiz5aBQAJ

I don't quite follow what you mean when you say you don't do initial bits?

**Comment by Thaina** [comment]
@stowy My code is exactly the same as `1.0.0` just import `1.2.2` into project make it cause this behaviour. So if this effect came from `not initializing the Mobile Ads SDK` then there would seem wrong

**Comment by stowy** [comment]
That's a fair comment.

The reason that I see the first log about MobileAds.initialize is because
in version 1.2.0 we added version support which queries the MobileAds
version for the AdMob adapter, and this causes the crash because you have
not initialized MobileAds.

The second crash seems more problematic from our side, this seems to
indicate an issue with the app ID. Are you launching the test suite using
the MediationTestSuite.launch(context, appId) API, without including an
appId in the android manifest? If so, that might explain the issue. But I'm
surprised that your app is launching without having an app ID in the
Android manifest, I would expect it to crash immediately by the Mobile Ads
SDK detecting no app ID in the manifest.

**Comment by Thaina** [comment]
@stowy Thanks for your suggestion. I would try those in my next workday

**Comment by Thaina** [comment]
Fixed. Thank you very much
