### ISSUE TITLE
RewardedAd only on iphoneXs don't show!

### ISSUE THREAD

**Issue by BuKuSiShen** [googleads/googleads-mobile-unity#1135]
All other iphone can always show RewardedAd.Plz help!

**Comment by BuKuSiShen** [comment]
Limit Ad Tracking is enabled.close this setting will show ewardedAd.

**Comment by ceceomer** [comment]
@BuKuSiShen how can I do that?

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now. If you are still experiencing the problem, please file a new issue with the same description, what happens and system / [network tracing](https://developers.google.com/admob/android/network-tracing) / [Charles](https://developers.google.com/admob/android/charles) logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution again!
