### ISSUE TITLE
Google Play API warnings

### ISSUE THREAD

**Issue by lux1111** [googleads/googleads-mobile-unity#1177]
Google Play Console Pre-Launch report shows ~10 Android compatibility warnings admob/gms using unsupported APIs. Which leads to crashes? Some apps get rejected.

[https://forum.unity.com/threads/google-play-api-warnings-started-today.676654/page-2#post-5136077](https://forum.unity.com/threads/google-play-api-warnings-started-today.676654/page-2#post-5136077)

I tried unity 2018.4, 2019.1, 2019.2, 2019.3, 2020, older and newest admob plugin. Every version comes with compatibility warnings, except 2020 it just crashes with admob package at launch.

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now. If you are still experiencing the problem, please file a new issue with the same description, what happens and system / [network tracing](https://developers.google.com/admob/android/network-tracing) / [Charles](https://developers.google.com/admob/android/charles) logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution again!
