### ISSUE TITLE
GoogleMobileAds-native Xcode Build Error

### ISSUE THREAD

**Issue by sezbladex** [googleads/googleads-mobile-unity#1181]
I am using Unity engine. I cant built on Xcode.  Xcode version is 10.2, I am getting undefined Symbol error. How can i fix this ? btw I tried enable bitcode No and enable modules objective c  Yes

![nyGk50](https://user-images.githubusercontent.com/7057236/75123377-e2a9bc80-56b7-11ea-812e-91b0b69b85e5.png)

**Comment by mdobele** [comment]
Which Unity version are you using?  My guess is the required AdMob frameworks haven't been included in your Xcode project.  Can you see the GoogleMobileAds.framework under the pods folder in your project navigator in Xcode?

**Comment by sezbladex** [comment]
Thank you for reply, I am using Unity2019 3.0f6,  I imported googlemobileads native package, there is no googlemobileads.framework, there is unity-plugin-library.a file, I am getting error this file. I have to add framework file ?

**Comment by mdobele** [comment]
Unity changed their XCode structure quite significantly in 2019.3 to support Unity integration into native iOS applications.  The "Unity-iPhone" target you may be used to is now a thin launcher which launches another main "UnityFramework" target which houses all the libraries etc

https://docs.unity3d.com/Manual/StructureOfXcodeProject.html

If you have upgraded from a previous Unity version, try deleting all of the Admob plugins and install the Admob Unity Plugin fresh again, make sure you're not doing any kind of post processing to your XCode project that was adding frameworks to the "Unity-iPhone" project or change those to target the "UnityFramework" instead.  

Also make sure you have the latest Google Play resolver integrated and everything setup correctly so that the iOS pod files are being added to your project correctly:

https://github.com/googlesamples/unity-jar-resolver

**Comment by sezbladex** [comment]
I solved problems, We have to add Googlemobileads.framework, after than add code to info.plist   
<key>GADIsAdManagerApp</key>
    <true />

Add Build settings 
Other Linker Flags   -ObjC
