### ISSUE TITLE
Troubleshoot ads not showing

### ISSUE THREAD

**Issue by boriestudiogames** [googleads/googleads-mobile-unity#1186]
I have read the document of admob: If you created a new ad unit recently, it may also take up to an hour before the ad unit is activated, ,In some cases, it may take longer than an hour for you to see ads in new apps or ad units.  But:
 -  I created ad units 2 days ago. 
 -  I also used test ad units to check my implementation and everything worked ok.
 -  I aslo confim PIN code by phone number and my accout is approved.
Currently, I use ad units instead of test ad unit, but my ads is not showing. I sure that ad unit is correctly.
 My information of ad unit for android:
  - AppId : ca-app-pub-1175004828811620~5350800695
  - Banner Id : ca-app-pub-1175004828811620/5737458282
  - Interstitial Id : ca-app-pub-1175004828811620/7980478242
Could you please help me this.
Thanks.

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now. If you are still experiencing the problem, please file a new issue with the same description, what happens and system / [network tracing](https://developers.google.com/admob/android/network-tracing) / [Charles](https://developers.google.com/admob/android/charles) logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution again!
