### ISSUE TITLE
Why I always get the error in android devices?

### ISSUE THREAD

**Issue by themoonbear** [googleads/googleads-mobile-unity#1224]
A scripted object (probably GoogleMobileAds.Editor.GoogleMobileAdsSettings?) has a different serialization layout when loading

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now. If you are still experiencing the problem, please file a new issue with the same description, what happens and system / [network tracing](https://developers.google.com/admob/android/network-tracing) / [Charles](https://developers.google.com/admob/android/charles) logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution again!
