### ISSUE TITLE
No compete callback after rewardAd

### ISSUE THREAD

**Issue by SmartProjectUser** [googleads/googleads-mobile-unity#1235]
I am using AdMob Mediation (5.0.1) on iOS platform and sometimes after complete watch Facebook Ad no close or reward callback fired and my application is freeze. I think app freeze because of use SetiOSAppPauseOnBackground(true) and that why application don't receive focus after ad at all.

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now. If you are still experiencing the problem, please file a new issue with the same description, what happens and system / [network tracing](https://developers.google.com/admob/android/network-tracing) / [Charles](https://developers.google.com/admob/android/charles) logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution again!
