### ISSUE TITLE
IronSource related ANRs

### ISSUE THREAD

**Issue by Ruco** [googleads/googleads-mobile-unity#1245]
We are experiencing several ANRs (some don't seem to even be logged in Google Play nor Crashlytics, just reported by users).
According to the changelog of IronSource SDK on their site, version 6.16.0 supposedly fixes this:

> ANR fix when using ironSource in 3rd party mediations

This is really impacting our ratings / performance metrics. So we would appreciate a speedy update of the Unity package for IronSource a lot.

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now. If you are still experiencing the problem, please file a new issue with the same description, what happens and system / [network tracing](https://developers.google.com/admob/android/network-tracing) / [Charles](https://developers.google.com/admob/android/charles) logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution again!
