### ISSUE TITLE
Incorrect work on 2019.3.9f1

### ISSUE THREAD

**Issue by IgorNebosenko** [googleads/googleads-mobile-unity#1250]
API don't correct works on this version(game loads near half minute, after - I can't see my banner).
After build example on device - crashes with fatal error

**Comment by stowy** [comment]
Can you please provide more information here? I have tested with 2019.3.3f1 with no issues.

Please include the version of the plugin you are using and the crash that you are seeing. Which platform and device are you running on as well?

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now. If you are still experiencing the problem, please file a new issue with the same description, what happens and system / [network tracing](https://developers.google.com/admob/android/network-tracing) / [Charles](https://developers.google.com/admob/android/charles) logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution again!
