### ISSUE TITLE
v5.1.0 Warnings

### ISSUE THREAD

**Issue by stan-osipov** [googleads/googleads-mobile-unity#1323]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2018.4.22f
  * Google Mobile Ads Unity plugin version: v5.1.0
  * Platform: Unity Editor
  * Platform OS version: MasOS 10.15.4
  * Any specific devices issue occurs on: no
  * Mediation ad networks used, and their versions: no

### [REQUIRED] Step 2: Describe the problem
2 Warnings are printed right after installation, that's very unpleasant experience especially for projects where warning treated as an error.

```
Assets/GoogleMobileAds/Platforms/iOS/RewardedAdClient.cs(64,46): warning CS0067: The event 'RewardedAdClient.OnAdStarted' is never used
```

```
There are inconsistent line endings in the 'Assets/GoogleMobileAds/Common/IInitializationStatusClient.cs' script. Some are Mac OS X (UNIX) and some are Windows.
This might lead to incorrect line numbers in stacktraces and compiler errors. Many text editors can fix this using Convert Line Endings menu commands.
```

#### Steps to reproduce:
Just install `v5.1.0` in the clean project.

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now. If you are still experiencing the problem, please file a new issue with the same description, what happens and system / [network tracing](https://developers.google.com/admob/android/network-tracing) / [Charles](https://developers.google.com/admob/android/charles) logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution again!
