### ISSUE TITLE
InterstitialAd is not showing in ios build

### ISSUE THREAD

**Issue by tejas-simprosys** [googleads/googleads-mobile-unity#1324]
I am trying to show InterstitialAd in my game but ads is not showing

environment which I used : 

  * Unity version: 2019.3.0f6
  * Google Mobile Ads Unity plugin version: 5.1
  * Platform: ios (iOS, Android, Unity Editor)
  * Platform OS version: ios 11 (eg iOS 10, Android 9)

problem : 
When I tyr to load InterstitialAd, it always went to onfailed callback. Error always have null message

I am getting following log : 

HandleFailedToReceiveAd event received with message: GoogleMobileAds.Api.AdFailedToLoadEventArgsGoogleMobileAds.Api.AdFailedToLoadEventArgs-1646332600Failed to receive ad with error: (null)
GoogleMobileAdsDemoScript:HandleOnAdFailedToLoad(Object, AdFailedToLoadEventArgs)

**Comment by thientv84** [comment]
I have the same problem, both InterstitialAd and banner

**Comment by stowy** [comment]
This is likely to be an issue with your ad units and account rather than Unity itself. I agree we need to improve the error messaging being passed through. Can you try using version 5.3.1 and also share logs from the Xcode console?

Also I'd like to note that these issues are for bugs in the plugin so if this is an issue related to your account / implementation you are best off posting an issue in our [developer forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).

**Comment by thientv84** [comment]
nope, 5.3.0 google admob sdk is the latest vesion

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now. If you are still experiencing the problem, please file a new issue with the same description, what happens and system / [network tracing](https://developers.google.com/admob/android/network-tracing) / [Charles](https://developers.google.com/admob/android/charles) logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution again!
