### ISSUE TITLE
Resolver ignores installed Ads package, generatig duplicated symbols

### ISSUE THREAD

**Issue by rsodre** [googleads/googleads-mobile-unity#1337]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2919.3.10
  * Google Mobile Ads Unity plugin version: 5.0.1
  * Platform: Android (iOS, Android, Unity Editor)
  * Platform OS version: min 12
  * Any specific devices issue occurs on: Unity Editor
  * Mediation ad networks used, and their versions: Unity Ads 3.4.5, adaptor 2.4.2
  * Resolver / External Dependency Manager version: 1.2.153

### Please describe the issue here:

I have installed Unity Ads version 3.4.5, from the Package Manager( com.unity.ads)
When I build for Android, the Resolver ignores it and dowmloads `com.unity3d.ads.unity-ads-3.4.2.aar`, causing a ton of duplicated symbols. I tried to update the package to 3.4.2, same version that is resolved, and the problem persists.

#### Steps to reproduce:

* Switch to Android Platform
* Install Unity Ads from the Package Manager
* Run the Resolver for Android > It will download the Unity Ads aar
* Build > Errors

The resolver should detect that the Unity Ads package is installed and use it instead of the lib.

After the build fails, if I delete `com.unity3d.ads.unity-ads-3.4.2.aar`, I can build successfully
But later on some build it will resolve the lib and fail again. I need to keep auto resolve before build Off.

Someone at Unity [suggested](https://forum.unity.com/threads/solved-duplicated-classes-when-building-for-android.857158/#post-5651995) that we should just remove the package, but I need the `UnityEngine.Advertisements` namespace on my scripts.

I tried opening a Resolver issue and was tols it's Google Ads responsibility to resolve and download only required libs.
https://github.com/googlesamples/unity-jar-resolver/issues/368

**Comment by stowy** [comment]
You can however manually edit the dependencies.xml file to remove the UnityAds dependency specified here:
https://github.com/googleads/googleads-mobile-unity/blob/master/mediation/UnityAds/source/plugin/Assets/GoogleMobileAds/Editor/UnityMediationDependencies.xml#L3

**Comment by rsodre** [comment]
The way I see it, as a user, is that the Resolver should be able to detect libs installed from packages (I asked many times and still don't know), and Google Ads should check if Unity Ads is already imported from a package. If that can't be done, then both teams should talk to each other and the resolving process be revised and updated, because a lot of plugins will be moving to packages and we'll soon have even more conflicts.

**Comment by chkuang-g** [comment]
@stowy 

Some input from the EDM4U side.

The issue is that [Unity Ads package](https://docs.unity3d.com/Packages/com.unity.ads@3.4/manual/index.html) comes with `com.unity3d.ads.unity-ads-***.aar` and they are not using EDM4U to resolve dependencies. 
On the other hand, [Unity Ads Mediation](https://github.com/googleads/googleads-mobile-unity/blob/master/mediation/UnityAds/source/plugin/Assets/GoogleMobileAds/Editor/UnityMediationDependencies.xml) depends on `com.google.ads.mediation:unity`, which might depends on `com.unity3d.ads.unity-ads-3.4.2`. 
As a result, if someone installs both mediation and Unity Ads, EDM4U cannot resolve the dependency because the `aar` from Unity Ads is pretty much out of the loop.

Also, given that Unity Ads can be installed through [Unity Package](https://docs.unity3d.com/Packages/com.unity.ads@3.4/manual/index.html) and [Asset Store](https://assetstore.unity.com/packages/add-ons/services/unity-monetization-66123#content), there is not an easy way to detect when Unity Ads is installed, especially when it is from Asset store. The solution would be for EDM4U to unpackage every loose `.aar` or `.jar` and see if there is any symbol conflict with any libraries managed by it.

I think the reasonable coarse of action is
1. Document this as a known issue and please confirm if removing the dependency [here](https://github.com/googleads/googleads-mobile-unity/blob/master/mediation/UnityAds/source/plugin/Assets/GoogleMobileAds/Editor/UnityMediationDependencies.xml#L3) still work. (as long as "androidPackage spec="com.google.ads.mediation:unity:3.4.2.3" is not required when Unity Ads is installed)
1. If someday the Mediation is available through Unity Package Manager, set `com.unity.ads` as the package dependency.

**Comment by rsodre** [comment]
I think mediation moving to Packages is innevitable in the current scenario, and will happen eventually.

The project I was working on is released. I'll have to do some updates soon, will try to test editing the dependency as you suggest.

**Comment by UnitySteven** [comment]
Part of the problem is that the package server via Package Manager or asset store is not what you need for mediation.  Google Play Resolver downloads the native distributions of the Unity Ads SDK for android and iOS which is then wrapped via an adaptor that bridges the Unity Ads SDK to the mediation product.  The packman package doesn't include this adaptor layer, which you need.

The packman package also is the direct integration of Unity Ads, and behaves by directly including the android and ios distributions of the Unity Ads SDK and then wrapping that with a C# wrapper layer that allows the developer to interact with the SDK.  This direct inclusion of the native ads sdk is where all your duplicate definitions are coming from when you try to use the packman package and google play resolver.

The Unity Ads Packman package and Asset Store package are basically the same thing, just served via different distribution channels.  Hope that helps clear up any confusion.

**Comment by rsodre** [comment]
I installed Unity Ads only from the Package Manager, not from the Asset Store. The duplicated symbols come from Google Resolver, it cannot identify Unity Ads package and downloads the Ads library again. I have to delete it manually after I use the Resolver.
