### ISSUE TITLE
BannerView.GetWidthInPixels() and BannerView.GetHeightInPixels() return wrong values on iPhone6P/7P/8P

### ISSUE THREAD

**Issue by abcjjy** [googleads/googleads-mobile-unity#1358]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.3.15f1
  * Google Mobile Ads Unity plugin version: 5.1.0
  * Platform: iOS
  * Platform OS version: iOS13.5
  * Any specific devices issue occurs on: iPhone 7 Plus
  * Mediation ad networks used, and their versions: NO

#### Steps to reproduce:

BannerView.GetWidthInPixels() and BannerView.GetHeightInPixels() return wrong value on iPhone7P. Unity player sets screen size to 1080x1920 on iPhone7P. However, these two methods return the size in 1242x2208 resolution. As a result, the returned size is always x1.15 larger than its actual size.

#### Relevant Code:

```
- (CGFloat)heightInPixels {
  return CGRectGetHeight(CGRectStandardize(self.bannerView.frame)) * [UIScreen mainScreen].scale;
}

- (CGFloat)widthInPixels {
  return CGRectGetWidth(CGRectStandardize(self.bannerView.frame)) * [UIScreen mainScreen].scale;
}
```

Replacing `[UIScreen mainScreen].scale` with `[UIScreen mainScreen].nativeScale` will fix this issue.

**Comment by ishnu47** [comment]
We have to customize the banner ad size in our game and we have to use `[UIScreen mainScreen].nativeScale` to have the expected size.

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now. If you are still experiencing the problem, please file a new issue with the same description, what happens and system / [network tracing](https://developers.google.com/admob/android/network-tracing) / [Charles](https://developers.google.com/admob/android/charles) logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution again!
