### ISSUE TITLE
"No Fill" in testing.

### ISSUE THREAD

**Issue by khdhhde21** [googleads/googleads-mobile-unity#1373]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.2.18f1
  * Google Mobile Ads Unity plugin version: v5.2.0
  * Platform: Android
  * Platform OS version: Android 8.0.0
  * Any specific devices issue occurs on: all
  * Mediation ad networks used, and their versions: none

#### Steps to reproduce:

The app has been using AdMob with no issues for over a year. The current version in Google Play shows all ads as expected.

Working on a new version of the app, noticed that the test version always returns **“no fill”** for all ads. 

#### Relevant Code:

```
    private AdRequest CreateAdRequest()
    {
        string deviceID = SystemInfo.deviceUniqueIdentifier;

        return new AdRequest.Builder()
            .AddTestDevice(AdRequest.TestDeviceSimulator)
            .AddTestDevice(deviceID)
            .TagForChildDirectedTreatment(true)                
            .AddExtra("tag_for_under_age_of_consent", "true")  
            .AddExtra("max_ad_content_rating", "G")            
                                                               
            .Build();
    }
```

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now. If you are still experiencing the problem, please file a new issue with the same description, what happens and system / [network tracing](https://developers.google.com/admob/android/network-tracing) / [Charles](https://developers.google.com/admob/android/charles) logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution again!

**Comment by manwithsteelnerves** [comment]
We also noticed No Fill response for test ad id's. Wondering why there needs to be a constraint for test ads too?
