### ISSUE TITLE
Freeze Enable jetpack ,forcing to change  to api 28

### ISSUE THREAD

**Issue by dominicdev** [googleads/googleads-mobile-unity#1423]
* Google Mobile Ads Unity plugin version: GoogleMobileAds-v5.3.0
  * Platform: Unity Editor building for android 
  * Platform OS version: Android (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: NO

where trying to build api 29 since gplay now required it this comming nov

![image](https://user-images.githubusercontent.com/3959917/90843068-5d1b7680-e393-11ea-93b3-75bf5db1bd3e.png)

**Comment by adix64** [comment]
Hi! If you switch the "Target API Level" to Automatic (Highest installed), it shouldn't ask you for enabling Jetpack.

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now. If you are still experiencing the problem, please file a new issue with the same description, what happens and system / [network tracing](https://developers.google.com/admob/android/network-tracing) / [Charles](https://developers.google.com/admob/android/charles) logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones.

Thanks for your contribution again!
