### ISSUE TITLE
Crash on com.google.unity.ads.Interstitial$1$1$1.run(Interstitial.java:82)

### ISSUE THREAD

**Issue by kaufcom** [googleads/googleads-mobile-unity#1432]
Hi,
We have this crash sometimes when we build with sdk 30 and google ads 5.3

Caused by java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Version '2019.4.9f1 (50fe8a171dd9)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'armeabi-v7a'
Build fingerprint: 'samsung/j7xeltexx/j7xelte:8.1.0/M1AJQ/J710FXXU5CRK3:user/release-keys'
Revision: '7'
ABI: 'arm'
Timestamp: 2020-08-28 10:03:17+0300
pid: 23843, tid: 24416, name: Thread-58  >>> com.anapp <<<
uid: 10245
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x2a
Cause: null pointer dereference
    r0  00000000  r1  c1ba4914  r2  b05db658  r3  b05db744
    r4  b05db744  r5  00000000  r6  00000000  r7  b05db658
    r8  00000003  r9  ba019800  r10 00000000  r11 b05db80c
    ip  c2ce542c  sp  b05db608  lr  c4bc9267  pc  c1bd9264

backtrace:
      #00 pc 0027a264  /data/app/com.kauf.talkingdonalddonkeyicefun--_E1zlIXyfZfWgiTizvBKg==/lib/arm/libil2cpp.so (BuildId: 28fe20a4781ad5ee7a648410b54aa35bfbf79c75)

       at libil2cpp.0x27a264()

Thread-57
       at com.unity3d.player.ReflectionHelper.nativeProxyInvoke()
       at com.unity3d.player.ReflectionHelper.a()
       at com.unity3d.player.ReflectionHelper$1.invoke(:31)
       at java.lang.reflect.Proxy.invoke(Proxy.java:913)
       at $Proxy8.onAdLoaded()
       at com.google.unity.ads.Interstitial$1$1$1.run(Interstitial.java:82)
       at java.lang.Thread.run(Thread.java:764)

Thx for your support
Roberto

**Comment by ttienqb** [comment]
the same. help me fix.
my user will drop

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now. If you are still experiencing the problem, please file a new issue with the same description, what happens and system / [network tracing](https://developers.google.com/admob/android/network-tracing) / [Charles](https://developers.google.com/admob/android/charles) logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones.

Thanks for your contribution again!
