### ISSUE TITLE
When will the Tapjoy adjustment unit be updated?

### ISSUE THREAD

**Issue by somiri** [googleads/googleads-mobile-unity#1448]
iOS 14 has been deployed and the corresponding Tapjoy SDK has been applied, but Mediation has not been deployed, making it impossible to test for sure. I wonder when it will be if I have a schedule.

Thank you.

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now. If you are still experiencing the problem, please file a new issue with the same description, what happens and system / [network tracing](https://developers.google.com/admob/android/network-tracing) / [Charles](https://developers.google.com/admob/android/charles) logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones.

Thanks for your contribution again!
