### ISSUE TITLE
Plugin version number missing from Unity files

### ISSUE THREAD

**Issue by kevinfoley** [googleads/googleads-mobile-unity#1451]
### [REQUIRED] Step 1: Describe your environment

Any

### [REQUIRED] Step 2: Describe the problem

There is no obvious file in the Unity plugin files (located at `source/plugin/Assets` in this repo) that indicates the version number of the plugin (e.g. v5.3.0). This makes it extremely difficult to determine which version of the plugin is installed when taking over an existing project. Please add releases notes or at least a VERSION.txt file to the  `source/plugin/Assets/GoogleMobileAds` directory

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now. If you are still experiencing the problem, please file a new issue with the same description, what happens and system / [network tracing](https://developers.google.com/admob/android/network-tracing) / [Charles](https://developers.google.com/admob/android/charles) logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones.

Thanks for your contribution again!
