### ISSUE TITLE
Support for Native Ads?

### ISSUE THREAD

**Issue by BonyYousuf** [googleads/googleads-mobile-unity#146]
Hi,
Can we have support for Native Ads on unity? Or can I please integrate Native ads on my own extending this sdk?

**Comment by ericleich** [comment]
The plugin is open-source, so you're always free to extend it to add features you want.

Native Ads is not yet in the plugin because of some technical limitations about the way the underlying Google Mobile Ads SDK works; it requires a special type of View to be placed in your view hierarchy for impression/click tracking. That doesn't really work in a Unity context if you want to deeply integrate raw text/image assets within your Unity scene. You'd still be limited to some view at the top or bottom of your game.

Supporting a better native ads integration is on our radar, but it requires effort on the underlying Google Mobile Ads SDK side to make it work well, and we're not there just yet.

**Comment by rampara** [comment]
Native Ads Advanced is now available through a [separate version](https://developers.google.com/admob/unity/native-advanced) of this plugin.
