### ISSUE TITLE
Not able to show the AppTrackingTransprency pop-up on iOS

### ISSUE THREAD

**Issue by JMartinSync** [googleads/googleads-mobile-unity#1504]
Hello,
I found some problems for making Unity able to build on iOS after updating to the last version:
1. AndroidManifest.xml not found
Solved editing ManifestProcessor.cs and changing the folder name where the file is
2. Cocoa Pods compatibility problems with Firebase
Solved editing GoogleMobileAdsDependencies and changing Google-Mobile-Ads-SDK version from 7.68 to 7.67

Now this is where Im stucked, I need to show the AppTrackingTransprency pop-up but and I have not idea how to do it.
As described [here](https://developer.apple.com/documentation/apptrackingtransparency)
I have added NSUserTrackingUsageDescription to the info.plist using an EntitlementPostProcess script, but I haven't found a requestTrackingAuthorization method for launch the popup...

**Comment by mdobele** [comment]
Admob has mentioned before that they don't have any plans on adding support for requesting iOS App Transparency in their plugin, I believe they are expecting Unity to provide a method to do that. 

In the meantime you will have to either write your own plugin, or use this plugin available on the Asset Store. 
https://assetstore.unity.com/packages/tools/integration/app-tracking-transparency-for-unity-ios-14-idfa-174256

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now. If you are still experiencing the problem, please file a new issue with the same description, what happens and system / [network tracing](https://developers.google.com/admob/android/network-tracing) / [Charles](https://developers.google.com/admob/android/charles) logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones.

Thanks for your contribution again!
