### ISSUE TITLE
When used with Playservices , Admob Banner ads shown behind (with opacity) 

### ISSUE THREAD

**Issue by fadsel** [googleads/googleads-mobile-unity#151]
The issue is related with admob also , check this issue 

https://github.com/playgameservices/play-games-plugin-for-unity/issues/891

To reproduce the error , download the game here

https://play.google.com/store/apps/details?id=com.fadsel.stickybubble

try submitting highscore or show leaderboard

**Comment by fadsel** [comment]
https://github.com/playgameservices/play-games-plugin-for-unity/issues/891

**Comment by ericleich** [comment]
The AdMob ad is part of the game activity. The play games plugin uses a transparent activity on top of the game activity when displaying achievements. So this is actually expected behavior.

It's infeasible to get the behavior you described, unless the play games plugin were to request an AdMob ads in their achievement activity. This won't ever happen in an official release -- you'd have to fork the plugin and add this yourself. I personally think the current behavior is better anyways.

**Comment by fadsel** [comment]
So what you are basically saying is that .... during all interactions with google play services , you can only get impressions? as in ... they cannot be clicked ... errm ... hows this better?

Is there a way to get the height of the GMS activity to be above the admob ads (ie. short ), as in like 60px above , 
Normally thats what we did for the main menu , it goes up a bit when the ads are ready , but thats because its kinda using the same activity .... when google play services starts its kinda freezing the whole unity activity , and I kinda dont know to override that. (I guess thats how it was meant to be)

So ... this is something i have to deal with :( , 

Thank you for your time.

**Comment by ericleich** [comment]
The way the google play services achievement is implemented, it's an entire screen (a.k.a. Activity in Android terms), which pauses the existing activity (the Unity game which includes the ad). The fact that the play games achievement activity is transparent is an implementation detail on the play games side, and was done for a cool effect effect. I don't know if there's a hook to turn that off or not and make it completely opaque. That's a better question for the play games folks.

As far as a workaround for ads, you could hide the banner when presenting the achievement activity, and show the banner again when coming back using the Hide() and Show() methods. Example calls are shown [here](https://developers.google.com/admob/android/games#showing_and_hiding_banners).

**Comment by fadsel** [comment]
I like the transparent idea , it gives a feeling to the user that its one of the menus of the game , i just dont like the idea that the ads are behind the GMS activity , the strange thing is that the ads do not freeze (admob does not freeze , it continues ) but my script freezes , 

as for Show() and Hide() , they only work in my activity inside unity , i have this implemented on gameplay , the ads are hiding and when the game is over or perhaps a user pauses .

The only solution that i can think of ... is how to get the ads behave as if they were requested by google play services ! - how can one pull that off?

Cheers

**Comment by ericleich** [comment]
The Show() and Hide() do only work inside your Unity activity, but your app should know when the app is about to display the achievements activity since you must be calling into play services to start it up. So before you do that, you can Hide() the ad in your game. And there must be some callback provided by the games plugin or at the Unity level to let you know your Unity activity is resuming, where you can call Show() again to present the ad again.

I agree that the only way you can get the behavior you originally desired is to make an ad request inside the google play services achievements activity. I'm not familiar enough with Google Play games to know if Google Play games open sources that activity as part of their plugin, but my guess is it's defined as part of Google Play services and not part of the play games plugin for Unity and is not exposed. In that case, you're blocked right there.

**Comment by fadsel** [comment]
So the only solution is to treat GooglePlayGames activity as Gameplay (since during gameplays ads are hidden and shown when user loses or pauses the game)

I will consider this as my last option that , i will try to mess around with the plugin for the meantime

Thank you  for your ideas .
