### ISSUE TITLE
Unity can't build ios

### ISSUE THREAD

**Issue by devflupin** [googleads/googleads-mobile-unity#1512]
getting this error on build an ios app

firebase 6.16
mopub sdk 5.15 ( + admob adapter)
admob sdk 5.4 

1. Google-Mobile-Ads-SDK 7.68 & MoPub-AdMob-Adapters 7.68.0.0
![1](https://user-images.githubusercontent.com/43026647/100082349-78fb5080-2e8b-11eb-9451-e54eaa3860b2.PNG)

2. Google-Mobile-Ads-SDK 7.66 & MoPub-AdMob-Adapters 7.66.0.0
![2](https://user-images.githubusercontent.com/43026647/100082609-caa3db00-2e8b-11eb-8084-c8b292245ca6.PNG)

I tried raising the firebase version to 7.1, but an unknown crash occurred and I am avoiding it.

Is there any other way to exclude the admob sdk?

**Comment by nghiadotuan** [comment]
Try change the version from 7.68 to 7.67 inside the xml file from the path Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml.
It's work with me

**Comment by devflupin** [comment]
@nghiadotuan 
Thank you.

I've tried it before but the pod install fails due to issues with MoPub-AdMob-Adapters version

I tried both MoPub-AdMob-Adapters and Google-Mobile-Ads-SDK versions "7.67", "7.66" and "7.68".

**Comment by stowy** [comment]
This looks like a duplicate of https://github.com/googleads/googleads-mobile-unity/issues/1495 regarding the conflict.

Regarding the second issue, you need to completely remove the plugin and the re-install version 5.3.0 it since you have still got updated iOS source files with references to `RewardedInterstitialAd` format which is not available in version 7.66.0.

**Comment by devflupin** [comment]
@stowy 

Thanks for the new way.

We will discuss and decide internally.

Thank you.
