### ISSUE TITLE
Feature Request: Implement Unity version of AdapterResponseInfo || GADAdNetworkResponseInfo

### ISSUE THREAD

**Issue by yerfdogj** [googleads/googleads-mobile-unity#1513]
Any chance that you have this on your roadmap?
Please add a Unity method to expose the underlying [AdapterResponseInfo](https://developers.google.com/android/reference/com/google/android/gms/ads/AdapterResponseInfo) (Android) or [GADAdNetworkResponseInfo](https://developers.google.com/admob/ios/api/reference/Classes/GADAdNetworkResponseInfo) (iOS) values.  Seems like it would be useful info when the mediated ad network reports an error.

**Comment by stowy** [comment]
@yerfdogj it is on our roadmap yes. Note that in the meantime the [`ToString()`](https://github.com/googleads/googleads-mobile-unity/blob/master/source/plugin/Assets/GoogleMobileAds/Platforms/iOS/ResponseInfoClient.cs#L62) method of [`ResponseInfo`](https://github.com/googleads/googleads-mobile-unity/blob/master/source/plugin/Assets/GoogleMobileAds/Api/ResponseInfo.cs#L34) will provide this information in a descriptive string you could log for example.

**Comment by yerfdogj** [comment]
Good to know. Thanks.

**Comment by SavaMinic** [comment]
Is there any news regarding this feature?
As I can see the underline code is there, just Unity wrappers need to be updated accordingly.

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now. If you are still experiencing the problem, please file a new issue with the same description, what happens and system / [network tracing](https://developers.google.com/admob/android/network-tracing) / [Charles](https://developers.google.com/admob/android/charles) logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones.

Thanks for your contribution again!
