### ISSUE TITLE
iOS Unity Cloud Build fails due to different XCode versions.

### ISSUE THREAD

**Issue by timeBenter** [googleads/googleads-mobile-unity#1519]
<img width="665" alt="Capture" src="https://user-images.githubusercontent.com/48895916/101119786-d20b7700-3637-11eb-93a8-d512d797ae51.PNG">

The build works perfectly without the plugin.
I am using the lastest release (5.4.0).

**Comment by stowy** [comment]
Hello @timeBenter, as per the issue template can you please ask this question on [our developer forum](https://groups.google.com/g/google-admob-ads-sdk) as it is not clear that it is an issue with the plugin code and we would need to see repro steps in order to determine whether this is an issue related to the plugin.
