### ISSUE TITLE
OnAdClickedEvent for Rewarded Videos

### ISSUE THREAD

**Issue by andpanda** [googleads/googleads-mobile-unity#1527]
* Unity version: 218.4.29
  * Google Mobile Ads Unity plugin version: 5.3.0
  * Platform: Both (iOS, Android, Unity Editor)
  * Platform OS version: N/A (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: N/A
  * Mediation ad networks used, and their versions: N/A

I need a callback to be able to report events of Rewarded Ad clicked to GA, but rewarded videos on admob does not have this callback, however interstitials do have it.
Did I miss something out? Or this feature is coming in the near future?
Thank You.

eg:
 this.rewardedAd.OnAdClicked

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now. If you are still experiencing the problem, please file a new issue with the same description, what happens and system / [network tracing](https://developers.google.com/admob/android/network-tracing) / [Charles](https://developers.google.com/admob/android/charles) logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones.

Thanks for your contribution again!
