### ISSUE TITLE
Frequency cap ignored when App Tracking is disallowed

### ISSUE THREAD

**Issue by mmouseenvelope12** [googleads/googleads-mobile-unity#1549]
* Unity version: 2017.4
  * Google Mobile Ads Unity plugin version: 5.4
  * Platform: iOS (iOS, Android, Unity Editor)
  * Platform OS version: iOS 14 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: iPhone 12

1. Use a 7 minute ad unit-level frequency cap
2. Freshly install and open app
3. Initialize AdMob
4. Request the App Tracking Transparency dialogue and select "Ask App Not to Track"
5. Cache, show, and dismiss an interstitial
6. Cache a new interstitial

Expected behavior would be for the cache to fail since it has been less than 7 minutes since the first interstitial was displayed. Instead, the SDK will successfully fill the cache request.

This would be a massive issue for any developer that relies on the AdMob frequency cap for pacing.

**Comment by mmouseenvelope12** [comment]
I suspect this is going to result in a lot of angry users, with a lot of angry developers to follow a day later.

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
