### ISSUE TITLE
Unexpected element <queries> found in <manifest>” when building

### ISSUE THREAD

**Issue by jmarisalandanan** [googleads/googleads-mobile-unity#1568]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.4.15f1
  * Google Mobile Ads Unity plugin version: 5.4.0
  * Platform: Android (iOS, Android, Unity Editor)
  * Platform OS version: NA
  * Any specific devices issue occurs on:NA
  * Mediation ad networks used, and their versions: 
Applovin 4.8.1
Facebook 3.2.0
Ironsource 2.0.3
Nend 4.0.0
Tapjoy 2.6.1
UnityAds 2.5.1
Vungle 3.5.1

#### Steps to reproduce:
After updating to Facebook Mediation 3.2.0, Android builds have started to fail with the error `Unexpected element <queries> found in <manifest>`. Downgrading Facebook Mediation to 3.1.0 fixes the issue, but would like to get to the bottom of this as this may also happen on future SDK updates. 

Any ideas on how to fix this?

**Comment by mdobele** [comment]
I believe this is because you're on an older version of Gradle that doesn't support the <queries> element.  If you're just using the version pre-installed with Unity you may need to force it up to the more recent patch versions to fix it.  You can read a little more on the issue here and which version to go to.

https://stackoverflow.com/questions/62969917/how-to-fix-unexpected-element-queries-found-in-manifest-error

**Comment by kapyar** [comment]
Yeah it might be the gradle problem. I had this problem before: I had gradle 3.3.0 version in my custom mainTemplate. After updating Admob to the 5.4.0 I had the same msg. What I did is changed gradle version in my mainTemplate to 3.3.4 and it solves the problem. The project was on Unity 2019.2.11. 
Some times later I updated it to 2020 lts and removed main template and it worked from the box.

**Comment by NVentimiglia** [comment]
Confirming this is a gradle issue and fixed by upgrading.
