### ISSUE TITLE
Google.JarResolver.ResolutionException

### ISSUE THREAD

**Issue by Triedge** [googleads/googleads-mobile-unity#157]
**Google.JarResolver.ResolutionException**: Cannot find candidate artifact for com.android.support:appcompat-v7:23.1.0+
  at **Google.JarResolver.PlayServicesSupport.DependOn** (System.String group, System.String artifact, System.String version) [0x00000] in <filename unknown>:0 
  at AdMobDependencies..cctor () [0x00039] in [Game Folder]\Assets\PlayServicesResolver\Editor\**AdMobDependencies.cs:21** 
UnityEditor.EditorAssemblies:**SetLoadedEditorAssemblies**(Assembly

**Comment by rampara** [comment]
Have you installed the specified version of the Android support library? 

- Ram

**Comment by Triedge** [comment]
Installed: 
- Google Mobile Ads Unity Plugin v3.0.
- google-play-services_lib

**Comment by rampara** [comment]
You no longer have to include the Google Play Services library project. The latest version of the Unity plugin uses the [JarResolver](https://github.com/googlesamples/unity-jar-resolver) plugin to resolve Google Play Service dependencies. The library relies on the installation of the Android Support Repository and the Google Repository SDK components. Can you try updating both of these components to the latest available and/ or set the version to be "LATEST" instead of "23.1.0+".

- Ram

**Comment by Triedge** [comment]
this... ?
![screenshot_35](https://cloud.githubusercontent.com/assets/5862340/12799619/5b67ec04-ca95-11e5-9c2b-afed5a1f2066.png)

**Comment by Triedge** [comment]
oh... nice!

**Comment by rampara** [comment]
Were you able to resolve this issue?

**Comment by Triedge** [comment]
Yes, yes, thx very much.

**Comment by rampara** [comment]
Glad you were able to get everything working.
