### ISSUE TITLE
OnUserEarnedReward is called after OnAdClosed in Unity editor

### ISSUE THREAD

**Issue by thsbrown** [googleads/googleads-mobile-unity#1571]
Step 1: Describe your environment

  * Unity version: 2018.4.30
  * Google Mobile Ads Unity plugin version: 5.4.0
  * Platform: Unity Editor 
  * Platform OS version: --
  * Any specific devices issue occurs on: Unity Editor
  * Mediation ad networks used, and their versions: --

Step 2: Describe the problem

#### Steps to reproduce:

`OnUserEarnedReward `event is called after `OnAdClosed `in editor. When built to device `OnUserEarnedReward `is called before `OnAdClosed`. After peeking around quite a bit online it seems as though `OnUserEarnedReward `should be called prior to `OnAdClosed `always. If this is the case the implementation in editor should reflect this :)

#### Relevant Code:

https://github.com/googleads/googleads-mobile-unity/blob/7a9bc72d6441edfe170fb9b4985cfbeede388772/source/plugin/Assets/GoogleMobileAds/Platforms/Unity/RewardingAdBaseClient.cs#L74-L84

**Comment by pabloivars** [comment]
On top of what @thsbrown has mentioned, the RewardAd prefab should have a button at all times to allow the user to close the ad without getting the reward.

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
