### ISSUE TITLE
Unity Mediation plugin adds full play-services-ads*.aar . I would like to use the play-services-ads-lite*.aar instead

### ISSUE THREAD

**Issue by moldovev** [googleads/googleads-mobile-unity#1583]
### [REQUIRED] Step 1: Describe your environment

  * Unity version:  2020.03_____
  * Google Mobile Ads Unity plugin version: _5.4.0____
  * Platform: __Android___ (iOS, Android, Unity Editor)
  * Platform OS version: any
  * Any specific devices issue occurs on: no
  * Mediation ad networks used, and their versions: Unity Mediation 2.6.0
  

### [REQUIRED] Step 2: Describe the problem

Using Unity Mediation plugin adds the full com.google.android.gms.play-services-ads-19.6.0.aar to my build even though without the mediation plugin, I am using com.google.android.gms.play-services-ads-lite-19.6.0.aar in my build.
I am using the LITE version of the plugin because size is critical for my app.

I would like to use the Unity Mediation plugin but with the LITE version of the ads ( https://developers.google.com/admob/android/lite-sdk )

Please advise how can I achieve this.

Thanks!

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
