### ISSUE TITLE
AppLovin Mediation plugin 4.8.1 is outdated

### ISSUE THREAD

**Issue by SuperUnityCoder** [googleads/googleads-mobile-unity#1593]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.4.21f1
  * Google Mobile Ads Unity plugin version: 5.4.0
  * Platform: iOS and Android (iOS, Android, Unity Editor)
  * Platform OS version: iOS 14.4.2, Android 10
  * Any specific devices issue occurs on: N/A
  * Mediation ad networks used, and their versions: AppLovin 4.8.1

### [REQUIRED] Step 2: Describe the problem

On app launch with Test Suite, warning appear in console:
* Android: 
```Current SDK version (9.14.6) is outdated. Please integrate the latest version of the AppLovin SDK (10.1.1). Doing so will improve your CPMs and ensure you have access to the latest revenue earning features.```
* iOS: 
```Current SDK version (6.14.6) is outdated. Please integrate the latest version of the AppLovin SDK (10.1.1). Doing so will improve your CPMs and ensure you have access to the latest revenue earning features.```

Please, update the plugin.

**Comment by amoswazana** [comment]
Same here.
Tried manually changing the AppLovinMediationDependencies.xml file to request version 10.1.1.0 of the AppLovin sdk but this caused issues with the pod install command.
Here is the error log:
`[!] CocoaPods could not find compatible versions for pod "Google-Mobile-Ads-SDK":
  In snapshot (Podfile.lock):
    Google-Mobile-Ads-SDK (= 7.69.0, >= 7.49.0, >= 7.52.0, >= 7.66.0, >= 7.67.0, >= 7.69.0, ~> 7.68)

  In Podfile:
    Google-Mobile-Ads-SDK (~> 7.68)

    GoogleMobileAdsMediationAppLovin (= 10.1.1.0) was resolved to 10.1.1.0, which depends on
      Google-Mobile-Ads-SDK (>= 8.3.0)

    GoogleMobileAdsMediationUnity (= 3.6.0.0) was resolved to 3.6.0.0, which depends on
      Google-Mobile-Ads-SDK (>= 7.69.0)
`

**Comment by HabibNasir** [comment]
Getting the Same Issue While Integrating Applovin Mediation.

**Comment by mdobele** [comment]
Additionally, Applovin tells me that the current version of the mediation plugin won't support iOS 14 ATT changes.

> _"The majority of your games are on AppLovin iOS SDK versions <10.0.0. These games will see a sharp decline in AppLovin network revenue when ATT rolls out, as these versions don't currently support both click and view-through SKA attribution functionality. To preserve your AppLovin revenue, please update these games to the latest AppLovin iOS SDK, v10.1.1, at your earliest convenience."

And after telling our Applovin account manager that we're using the latest plugin available to us and that it hadn't been updated yet.

> _"You are right--it doesn't seem that the adapter has been updated for a while. We've contacted Admob about the timetable for the newest adapters, and they've told us it will be made available the last week of April."

**Comment by sologamer** [comment]
Anyone knows when the AppLovin mediation plugins gets an update? 

Apparently we are unable to build now due to the CocoaPods specs source links to a forbidden 403 page due to the bintray shutdown. Anyone knows a solution on how to (temporarily) solve the forbidden source issue?

https://github.com/CocoaPods/Specs/blob/master/Specs/7/5/f/GoogleMobileAdsMediationAppLovin/6.14.9.0/GoogleMobileAdsMediationAppLovin.podspec.json

**Comment by amoswazana** [comment]
Any updates on this? Maybe someone from the AdMob team can chime in?

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
