### ISSUE TITLE
Crashes GADNetwork enableRadioAccessTechnologyChecking

### ISSUE THREAD

**Issue by a314266177** [googleads/googleads-mobile-unity#1595]
GADNetwork enableRadioAccessTechnologyChecking
![image](https://user-images.githubusercontent.com/18459275/115540455-a4feee80-a2d0-11eb-8b67-c7a5a1c522a2.png)

I'm using Unity GMA 5.3.0, is there a solution to this problem?

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
