### ISSUE TITLE
GMA Unity v6.0.0 - Facebook Mediation Problem - Android Armv7 

### ISSUE THREAD

**Issue by aceloq** [googleads/googleads-mobile-unity#1630]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.4.26f1
  * Google Mobile Ads Unity plugin version: 6.0.0
  * Platform: Android
  * Platform OS version: 7.1.1
  * Any specific devices issue occurs on: Armv7 devices
  * Mediation ad networks used, and their versions: Facebook Mediation Adapter 3.2.0

#### Steps to reproduce:

It works well on Arm64 android devices. But, on Armv7 android devices, admob works but Facebook ads doesn't work. When I check it from Ad Inspector, Facebook ad requests do not respond. It gives error "1001 : No Fill".
The version of my app on the Google Play Store has Google Mobile Ads Unity Plugin v5.4.0 with Facebook Mediation Adapter 3.2.0 and when I tested it, works well on armv7 android devices.

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
