### ISSUE TITLE
GMA Unity v6.0.0 - Applovin Mediation 5.0.0 - Regarding the problem that the app freezes when viewing the Applovin ad

### ISSUE THREAD

**Issue by crSudo** [googleads/googleads-mobile-unity#1638]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2018.4.27f1 (64-bit)
  * Google Mobile Ads Unity plugin version: 6.0.0
  * Platform: iOS (iOS, Android, Unity Editor)
  * Platform OS version: iOS 14.5
  * Mediation ad networks used, and their versions: AppLovin Unity Mediation Plugin 5.0.0

### [REQUIRED] Step 2: Describe the problem
On an iOS 14.5 device, changing [Settings]-[Region] to [Italy] and playing the [Applovin] ad causes the app to freeze. * Run RewardedAd.Show ()

#### Steps to reproduce:
1. Use an OS 14.5 terminal.
2. Set iPhone [Settings]-[Region] to [Italy].
3. Play Applovin ads. * Execute RewardedAd.Show ()

There was a problem that the screen freezes.
This symptom occurred in both Rewarded and Interstitial.

[inspection result]
◇OS
Only occurs in 14.5.

* It did not occur in the following OS.
・ 14.6
・ 10.3.3
・ 11.0.3

◇Country
·Italy
·Germany
·Spain
Occurs in.

* It did not occur in the following countries.
·Japan
·America
·England
* Other countries have not been verified.

◇SDK Each Version verification
I tried updating the Applovin SDK, but I couldn't solve the problem.
・ Pod'GoogleMobileAdsMediationAppLovin', '10.1.1.0'
・ Pod'GoogleMobileAdsMediationAppLovin', '10.3.0.0'

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
