### ISSUE TITLE
Multiple precompiled assemblies with the same name Google.VersionHandler.dll included or the current platform. 

### ISSUE THREAD

**Issue by fiqryq** [googleads/googleads-mobile-unity#1659]
how to solve error code below ? i try to delete google.version handler but still error.
Multiple precompiled assemblies with the same name Google.VersionHandler.dll included or the current platform. Only one assembly with the same name is allowed per platform. (Assets/PlayServicesResolver/Editor/Google.VersionHandler.dll)

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
