### ISSUE TITLE
Game Slowing when the ads banner is showing !!!

### ISSUE THREAD

**Issue by lahmidi-developer** [googleads/googleads-mobile-unity#1660]
The problem I have is when the banner ad appears,
As the game **becomes very slow**, especially when an advertisement containing Animation !!!
any one cane help ??
  * Unity version: 2019.1.26f1
  * Google Mobile Ads Unity plugin version: 5.4.0
  * Platform: Android

**Comment by mrad00** [comment]
o

**Comment by xebudda** [comment]
Bannerviews causing memory problems even in empty scenes and empty projects for me.

Every time bannerview opens and refreshes it gives chromium memory error

I call bannerview once in script in start

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
