### ISSUE TITLE
Error installing GoogleMobileAdsMediationFacebook - url for FacebookAdapter-6.2.0.0.zip is forbidden which fails the cocoapod install

### ISSUE THREAD

**Issue by murali-omio** [googleads/googleads-mobile-unity#1686]
### [REQUIRED] Step 1: Describe your environment

  * Google Mobile Ads Unity plugin version: 7.68.0
  * Platform: iOS
  * Platform OS version: iOS 14.5
  * Any specific devices issue occurs on: Cocoapod install
  * Mediation ad networks used, and their versions: _____

#### Steps to reproduce:

While trying to install Google-Mobile-Ads-SDK 7.68.0, it installs GoogleMobileAdsMediationFacebook 6.2.0.0 as a dependency which fails during `pod install`

Not able to reach this URL: [https://google.bintray.com/mobile-ads-adapters-ios/FacebookAdapter/6.2.0.0/FacebookAdapter-6.2.0.0.zip](https://google.bintray.com/mobile-ads-adapters-ios/FacebookAdapter/6.2.0.0/FacebookAdapter-6.2.0.0.zip)
<img width="571" alt="AdsSDK" src="https://user-images.githubusercontent.com/58173905/124618314-f94d4f80-de77-11eb-8d50-f5bc60902f79.png">

**Comment by NVentimiglia** [comment]
Hi there,

Can you try running `pod update' ?

This url was updated here :
https://github.com/CocoaPods/Specs/commit/ba0426d6e74df698b5a1bc1af240a0688589f281#diff-5fa37f8ad72327637bc1c20dcfce20e4378ae3fbc24d12c8d00a0d9926d85d28

**Comment by murali-omio** [comment]
Hello @NVentimiglia ,

Yes, I tried that but I still get the error. Even when I use pod 'GoogleMobileAdsMediationFacebook', '6.2.0.0' directly, it still tries to fetch it from the old bintray link which is not available.

**Comment by ericleich** [comment]
@murali-omio That's odd, the only way I could see that happening is if you have something cached on your machine.

When you do a `pod update` or a `pod repo update`, it should update the latest podspecs on your machine. For me, that lives at `~/.cocoapods/repos/master/Specs/4/1/b/GoogleMobileAdsMediationFacebook/6.2.0.0/`. If you look at the podspec for that version, it should point to the dl.google.com URL and not the bintray.com URL if your local repo has been updated since April 30th.

**Comment by murali-omio** [comment]
@ericleich Thanks a lot for the suggestion. I tried both `pod update` and `pod repo update` but it did not update the URL in the trunk or master branch. After manually deleting the specs in the path, it was able to pick the updated link.
