### ISSUE TITLE
mediation sdk download link is not working

### ISSUE THREAD

**Issue by lockerprime** [googleads/googleads-mobile-unity#1707]
i tried to download mediation sdk . link is not navigating to download sdk location. Please check it out. i want to download mediation adapters..

currently its navigating to this url :https://jfrog.com/center-sunset/#files/GoogleMobileAdsUnityAdsMediation

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
