### ISSUE TITLE
Conflict with another plugin (InAppBrowser downloadble from asset store)

### ISSUE THREAD

**Issue by ddadkhah** [googleads/googleads-mobile-unity#1775]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.18f1
  * Google Mobile Ads Unity plugin version: 6.1.0
  * Platform: Android
  * Platform OS version: Any (Tested on android 10)
  * Any specific devices issue occurs on: Any (tested on Xperia XZ1)
  * Mediation ad networks used, and their versions: not used

### [REQUIRED] Step 2: Describe the problem
When I use admob unity plugin version 6.1.0 simultaneously with InAppBrowser plugin (downloadble from unity asset store), that plugin return an error when I try to open a web page in the app. The error is "java.lang.classnotfoundexception" "com.kokosoft.helper".
When I downgrade admob unity plugin to 6.0.0 it works correctly.
I think the problem is because of the admob unity plugin. 

#### Steps to reproduce:
Sorry I didn't have time to see how you can reproduce it. 
You can download in app browser plugin from https://assetstore.unity.com/packages/tools/gui/in-app-web-browser-57532

**Comment by NVentimiglia** [comment]
Hi @ddadkhah,

Can you find and upload the dependencies required for in-app-web-browser ?

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
