### ISSUE TITLE
Custom size banner crash

### ISSUE THREAD

**Issue by CsabaStupak** [googleads/googleads-mobile-unity#1779]
* Unity version: 2020.3.11f1
  * Google Mobile Ads Unity plugin version: 6.1.0
  * Platform: Unity Editor
  * Platform OS version: Android 9

I would like to control the Banner exact position and size in my game. According to documentation - Banner\Get started\Optional (custom)ad sizes it should be possible. I create the Banner as follows:

```
void CreateMyBanner(Bounds rcBanner)
{
	m_bannerView = new BannerView(
		Factory.BannerID,
		new AdSize((int)rcBanner.size.x, (int)rcBanner.size.y),
		(int)rcBanner.min.x, (int)rcBanner.min.y);

	...
}
```

The result is exception:

```
"The given key was not present in the dictionary."

at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x0001e] in <695d1cc93cca45069c528c15c9fdd749>:0 
at GoogleMobileAds.Unity.BannerClient.CreateBannerView (System.String adUnitId, GoogleMobileAds.Api.AdSize adSize, System.Int32 x, System.Int32 y) [0x0001c] in <0e2a8f165b664a1c8901be01b8d2d4bf>:0 
at GoogleMobileAds.Api.BannerView..ctor (System.String adUnitId, GoogleMobileAds.Api.AdSize adSize, System.Int32 x, System.Int32 y) [0x00016] in <cd14da82da80481c8b544217b19acede>:0 
```

When I create such custom `AdSize`, its type is `AdType = Standard`. Looking at the `GoogleMobileAds.Unity.BannerClient` `prefabAds` dictionary there are no such item which causes the crash.

**Comment by dareerahmadmufti** [comment]
This issue is Editor only issue. As current version of Admob, try to show dummy ad on the screen by instantiating the ad prefab from the "GoogleMobileAds > Editor > Resources > DummyAds > -From appropriate ad type folder here-", for the ease of developer to seeing the ads impact on the editor (means how ad will be shown in the actual app).
So, on actual device, it will not cause any issue at all (the error won't happen), as there it will request ad from the server to show an ad (will not do prefab stuff*).

But 2 things to remember: 
p1 - actual ads on the devices served in the terms of DPI and these prefab works on the basics on Pixels on editor. 
p2 - your code will not work properly, as you are passing the pixels (RectTransform bounds) as banner size. It will work on the editor, but on the actual device, it will far way bigger, and position will be far way from the viewing area from screen, due to p1 as mentioned above. So you need to convert these pixels to DPI on the actual device (android - iOS), to set custom positions and size.
