### ISSUE TITLE
GoogleMobileAdsSettings reset automatically in v6.1.1

### ISSUE THREAD

**Issue by abcjjy** [googleads/googleads-mobile-unity#1801]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.4.29
  * Google Mobile Ads Unity plugin version: 6.1.1
  * Platform: UnityEditor
  * Platform OS version: iOS14
  * Any specific devices issue occurs on: Editor
  * Mediation ad networks used, and their versions: No

#### Steps to reproduce:

1. Set GoogleMobileAdsSettings
2. Run in editor
3. GoogleMobileAdsSettings is reset to empty

#### Relevant Code:

In GoogleMobileAdSettings.cs, following code reset settings whenever instance == null and discards the loaded data from Resource dir.

```
        public static GoogleMobileAdsSettings Instance
        {
            get
            {
                if (instance != null)
                {
                    return instance;
                }

                instance = Resources.Load<GoogleMobileAdsSettings>(MobileAdsSettingsFile);

                Directory.CreateDirectory(MobileAdsSettingsResDir);

                instance = ScriptableObject.CreateInstance<GoogleMobileAdsSettings>();

                string assetPath = Path.Combine(MobileAdsSettingsResDir, MobileAdsSettingsFile);
                string assetPathWithExtension = Path.ChangeExtension(
                                                        assetPath, MobileAdsSettingsFileExtension);
                AssetDatabase.CreateAsset(instance, assetPathWithExtension);

                return instance;
            }
        }
```

**Comment by pedro15** [comment]
I fixed this in my version, also i've made a pull request with the fix, hopefully google will merge it in the next release.
See my pull request: #1803

It is basically 2 files changed, the GoogleMobileAdsSettingsEdtior and The GoogleMobileAdsSettings:

In the GoogleMobileAdsSettingsEditor they were trying to save the changes made in the inspector using SetDirty, that was not the correct way to do that, the correct way is by using serializedProperty. 

And in the GoogleMobileAdsSettings is the stuff that you are pointing out, each time that you try to edit settings they are creating a new instance, so that is wrong, i added an if to validate if no settings found, then create a new one, not every time.

**Comment by scorp2007** [comment]
same problem with 2021.1.26f1 and 2021.1.25f1

**Comment by smt923** [comment]
> same problem with 2021.1.26f1 and 2021.1.25f1 and GoogleMobileAds-v6.1.2.unitypackage

getting the same issue on 2021.1.28f1, have to paste in my app ID in almost every time I have to build

**Comment by MarkMa-LS** [comment]
My Fix:
Move GoogleMobileAdsSettings.asset file from **Assets\GoogleMobileAds\Resources\** to **Assets\** and configure it

**Comment by egorovsa** [comment]
The same unity 2021, 
v.6.1.2

**Comment by G-r-i-n-c-h** [comment]
Its Already 3 Month its not fixed and we need to thanks @pedro15 ! take this guys code and fix this **** !

**Comment by pedro15** [comment]
> Its Already 3 Month its not fixed and we need to thanks @pedro15 ! take this guys code and fix this **** !

You're welcome :) i'm glad that my fix is helping the community.

**Comment by Nyankoo** [comment]
Still happening in 7.0.0 :'D

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
