### ISSUE TITLE
SetApplicationMuted () triggers "Trying to set volume before player is initialized." error

### ISSUE THREAD

**Issue by eduardocoelho** [googleads/googleads-mobile-unity#1802]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.16f1
  * Google Mobile Ads Unity plugin version: 6.1.1
  * Platform: Android
  * Platform OS version: Android 12
  * Any specific devices issue occurs on: All
  * Mediation ad networks used, and their versions: None

#### Steps to reproduce:

Unable to mute ads. I'm invoking `MobileAds.SetApplicationMuted ()` both *before* and *after* `InterstitialAd.OnAdOpening`; in both cases the following message appears on the android logcat `10-15 11:48:05.146 20833 20833 W Ads     : Trying to set volume before player is initialized.`

How can I ensure ads are shown to my users without audio (or with the 'mute' button) already toggled?

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
