### ISSUE TITLE
A lot of issues in Documentation

### ISSUE THREAD

**Issue by Volodymyr-13** [googleads/googleads-mobile-unity#1816]
I don't know where I can post this bug publicly, so posting here. 
I already reported via some other methods, 1 month ago, but as I see - no one cares. 

1. A lot of mediation networks documentation is outdated, I will not describe which and where, just check all them.
2. Almost in all documentation images are rotated 90: 
https://developers.google.com/admob/unity/mediation/adcolony

<img width="751" alt="Screenshot 1" src="https://user-images.githubusercontent.com/3391456/138062400-a1841539-105a-41d6-a0c4-408852b77e9a.png">

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
