### ISSUE TITLE
latest admob plugin crash 

### ISSUE THREAD

**Issue by stickylabdev** [googleads/googleads-mobile-unity#1864]
please accept the fact that the latest version has a lot of errors and crashes, even the tutorial says so https://www.youtube.com/watch?v=kMne8YNoTms

**Comment by mjshin82** [comment]
I have the same issue (https://github.com/googleads/googleads-mobile-unity/issues/1818) on Mac M1, 2021.2
Do you also use firebase? 
When I only import admob plugin to the empty project, it was fine.
But after importing firebase to the same project, then it crashes.

**Comment by stickylabdev** [comment]
Only admob. No firevas

Pada tanggal Sen, 29 Nov 2021 18.01, mj.shin ***@***.***>
menulis:

**Comment by NVentimiglia** [comment]
@stickylabdev 

Hi, I would like to help with any errors or crashed. If you could include a log or exception message, that would help me diagnose the issue.

**Comment by stickylabdev** [comment]
> @stickylabdev
> 
> Hi, I would like to help with any errors or crashed. If you could include a log or exception message, that would help me diagnose the issue.

sorry for late reply ,,,,,,,, come here please sir https://github.com/googleads/googleads-mobile-unity/issues/2000

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
