### ISSUE TITLE
Interstitial ad only show once on IOS.

### ISSUE THREAD

**Issue by Hoffa25** [googleads/googleads-mobile-unity#189]
With Android this error dont happen...

With ios, after the first time I destroy the ad and try to loadAd again but nothing happens and the ad never get reloaded. In xcode debugger there is absoluteley no error message or anything when I try to reload.

I have Unity 5.3.3 and plugin version 3.0.2

**Comment by rampara** [comment]
On iOS, GADInterstitial is a one time use object. Since the Google Mobile Ads Unity plugin is a wrapper for the Google Mobile Ads Unity SDK, the same limitations apply. You can find more information on our [developer docs](https://developers.google.com/admob/ios/interstitial#only_load_gadinterstitial_once). Every time you make a interstitial ad request, you should use a new interstitial object. Our [sample project](https://github.com/googleads/googleads-mobile-unity/blob/master/samples/HelloWorld/Assets/GoogleMobileAdsDemoScript.cs) is a good example for what best practice should be.

**Comment by yothin** [comment]
Same problem, I try load new request OnAdClosed delete but not work.

**Comment by rampara** [comment]
You will need to create a new InterstitalAd object. Our sample application linked above is a good example for what best practice should be.

**Comment by skopekreep** [comment]
Heads up, the link for the sample application is broken.  Thanks for updating it when you can.
