### ISSUE TITLE
Custom data and User id doesn't exists when callback URL is called

### ISSUE THREAD

**Issue by ddadkhah** [googleads/googleads-mobile-unity#1892]
* Unity version: 2020.3.18f1
  * Google Mobile Ads Unity plugin version: 6.1.2
  * Platform: Android (not tested on other platforms)
  * Platform OS version: All versions
  * Any specific devices issue occurs on: Sony experia XZ1
  * Mediation ad networks used, and their versions: Admob

I set the user id and custom data on the client side. But these two parameters are not sent to the callback URL by the Admob. All other parameters are sent.
This is the related post in the Admob Group: https://groups.google.com/g/google-admob-ads-sdk/c/NVffEJUMUso

**Comment by aimatme** [comment]
Same issue in googleads-mobile-unity 6.0.1

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
