### ISSUE TITLE
AndroidJavaException: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by JACLEMGO** [googleads/googleads-mobile-unity#193]
Running my unity game on nexus 7, getting the following error:
03-25 00:12:13.560: I/Unity(14006): AndroidJavaException: java.lang.NoSuchMethodError: no method with name='setRequestAgent' signature='(Ljava/lang/String;)Ljava/lang/Object;' in class Lcom/google/android/gms/ads/AdRequest$Builder;

Anyone know how to solve it? 

Setup:
Unity 5.3.2
Latest Google Mobile Ads Plugin.
Facebook
VoxelBusters Native Plugins
Chartboost

**Comment by rampara** [comment]
Can you provide a link to a Unity project where this error can be reproduced?

**Comment by subzeroz** [comment]
Have you solved this issue ?

**Comment by rampara** [comment]
@subzeroz Can you provide a link to a Unity project where this error can be reproduced? What version of Google Play Services is installed on the device you are using?

**Comment by subzeroz** [comment]
Here is the package of a test project:

[https://www.dropbox.com/s/s4rianj1uszcfms/AdmobTest.unitypackage?dl=0](https://www.dropbox.com/s/s4rianj1uszcfms/AdmobTest.unitypackage?dl=0)

(I deleted my AdUnit Ids in the script attached to the camera. Please try it with your AdUnit Ids instead)

I also noticed something in my Admob account, and that is they showed me a note that the ads are not showing because I haven't verified my account yet. They should send me a PIN Code, but still didn't receive one yet. I don't know if this has to do with the error I am getting.

Thanks in advance.

**Comment by JACLEMGO** [comment]
sorry for the delay, I solved the issue by replacing the google play services in the unity project with the latest google play services.

**Comment by rampara** [comment]
Glad you were able to resolve this issue.
