### ISSUE TITLE
Lag 3 seconds after invoke show interstitial on Android

### ISSUE THREAD

**Issue by IgorGalimski** [googleads/googleads-mobile-unity#1948]
* Unity version: 2020.3.20f1
  * Google Mobile Ads Unity plugin version: 6.1.2
  * Platform: Android (iOS, Android, Unity Editor)
  * Platform OS version: 11(eg iOS 10, Android 9)
  * Any specific devices issue occurs on: Samsung, Xioami
  * Mediation ad networks used, and their versions: 
mopub:5.18.0.0
applovin:10.3.2.0
chartboost:8.2.1.0
facebook:6.7.0.0
tapjoy:12.8.1.0
unity-ads:3.7.5
vungle:6.9.1.1
inmobi:9.2.0.0
fyber:7.8.3.0
ironsource:7.1.8.0

### [REQUIRED] Step 2: Describe the problem

After we click to show the interstitial -we have a lag on the main thread for 3 seconds. After this - the interstitial is shown
What can be the reason?
<img width="1406" alt="Screenshot 2022-03-03 at 7 59 22 PM" src="https://user-images.githubusercontent.com/19680568/156745671-0ff54b6d-5462-4201-83c9-d54fd26bf360.png">

#### Relevant Code:

We use usual code to requests and load ads
```
                var request = new GoogleMobileAds.Api.AdRequest.Builder().Build();
                _interstitialAd.LoadAd(request);
```

**Comment by IgorGalimski** [comment]
Ping

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
