### ISSUE TITLE
Rewarded ADs Issue.

### ISSUE THREAD

**Issue by iamferozi** [googleads/googleads-mobile-unity#2060]
There is no event to know if the user had skipped the ad.

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
