### ISSUE TITLE
7.0.1 iOS : unity-plugin-library.a missing armv7

### ISSUE THREAD

**Issue by seokwanhee** [googleads/googleads-mobile-unity#2066]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2018.4.31f1
  * Google Mobile Ads Unity plugin version: 7.0.1
  * Platform: iOS (iOS, Android, Unity Editor)
  * Platform OS version: iOS 10 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: facebook (6.9.0.1), vungle (6.9.2.0)

#### Steps to reproduce:

What happened? How can we make the problem occur?

XCode Build Error : The linked library 'unity-plugin-library.a' is missing one or more architectures required by this target: armv7.

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

Unlike 7.0.0, unity-plugin-library.a does not have armv7 architecture. The following is the file information.

$file unity-plugin-library.a
unity-plugin-library.a: Mach-O universal binary with 2 architectures: [x86_64:current ar archivecurrent ar archive] [arm64:current ar archivecurrent ar archive]
unity-plugin-library.a (for architecture x86_64): current ar archive
unity-plugin-library.a (for architecture arm64): current ar archive

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
