### ISSUE TITLE
CommandInvokationFailure: Failed to re-package resources. See the Console for details.

### ISSUE THREAD

**Issue by gitizenme** [googleads/googleads-mobile-unity#212]
See [https://github.com/gitizenme/Unity-AdMob-Fail] for Unity Project that fails to build.
Below are 2 errors reported by Unity when running an Android build.

```
CommandInvokationFailure: Failed to re-package resources. See the Console for details.
C:\Program Files (x86)\Android\android-sdk\build-tools\23.0.3\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:/Program Files (x86)/Android/android-sdk\platforms\android-23\android.jar" -F bin/resources.ap_ --extra-packages com.google.unity

stderr[
AndroidManifest.xml:16: error: Error: No resource found that matches the given name (at 'theme' with value '@style/Theme.IAPTheme').

AndroidManifest.xml:18: error: Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

]
stdout[
Configurations:
 (default)
 v14
 v21
 xhdpi-v4

Files:
  drawable\app_banner.png
    Src: (xhdpi-v4) res\drawable-xhdpi\app_banner.png
  drawable\app_icon.png
    Src: () res\drawable\app_icon.png
  values\strings.xml
    Src: () res\values\strings.xml
  values\styles.xml
    Src: () res\values\styles.xml
    Src: (v14) res\values-v14\styles.xml
    Src: (v21) res\values-v21\styles.xml
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
  Type drawable
    drawable\app_banner.png
      Src: (xhdpi-v4) res\drawable-xhdpi\app_banner.png
    drawable\app_icon.png
      Src: () res\drawable\app_icon.png
  Type values
    values\strings.xml
      Src: () res\values\strings.xml
    values\styles.xml
      Src: () res\values\styles.xml
      Src: (v14) res\values-v14\styles.xml
      Src: (v21) res\values-v21\styles.xml
Including resources from package: C:\Program Files (x86)\Android\android-sdk\platforms\android-23\android.jar
applyFileOverlay for drawable
applyFileOverlay for layout
applyFileOverlay for anim
applyFileOverlay for animator
applyFileOverlay for interpolator
applyFileOverlay for transition
applyFileOverlay for xml
applyFileOverlay for raw
applyFileOverlay for color
applyFileOverlay for menu
applyFileOverlay for mipmap
Processing image: res\drawable-xhdpi\app_banner.png
Processing image: res\drawable\app_icon.png
    (processed image res\drawable\app_icon.png: 94% size of source)
    (processed image res\drawable-xhdpi\app_banner.png: 93% size of source)
    (new resource id app_banner from xhdpi-v4\drawable\app_banner.png #generated)
    (new resource id app_icon from drawable\app_icon.png #generated)
]
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.PostProcessAndroidPlayer.Exec (System.String command, System.String args, System.String workingdir, System.String[] progress_strings, Single progress_value, System.String errorMsg)
UnityEditor.Android.PostProcessAndroidPlayer.CompileResources (System.String stagingArea, System.String packageName, UnityEditor.Android.AndroidLibraries androidLibraries)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcessInternal (System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry)
UnityEditor.HostView:OnGUI()
```

```
Google.JarResolver.ResolutionException: Cannot find candidate artifact for com.google.android.gms:play-services-ads:LATEST
  at Google.JarResolver.PlayServicesSupport.DependOn (System.String group, System.String artifact, System.String version) [0x00000] in <filename unknown>:0 
  at AdMobDependencies..cctor () [0x00024] in C:\Users\joe.chavez\Documents\Personal\Projects\admob\AdMob\Assets\PlayServicesResolver\Editor\AdMobDependencies.cs:18 
UnityEditor.EditorAssemblies:SetLoadedEditorAssemblies(Assembly[])
```

**Comment by gitizenme** [comment]
I deleted files listed below and the build completed and ran on the target Android device successfully.
```
https://github.com/gitizenme/Unity-AdMob-Fail/blob/master/AdMob/Assets/Plugins/Android/GoogleMobileAdsPlugin/libs/PLUGIN_JAR_GOES_HERE
https://github.com/gitizenme/Unity-AdMob-Fail/blob/master/AdMob/Assets/Plugins/Android/GoogleMobileAdsPlugin/libs/PLUGIN_JAR_GOES_HERE.meta
```

**Comment by 850176300** [comment]
yeah, I have the same question. This solution is not work for me. Can you give me a favor? Thank you!

**Comment by rampara** [comment]
@gitizenme Looks JarResolver didn't run yet for your project. Deleting the files you mentioned (which shouldn't change any behavior) kicked off JarResolver. You can manually run JarResolver via `Assets->Google Play Services->Resolve Client Jars` in the Editor menu. @850176300 does this resolve your issue as well?

**Comment by prasmitrajigare** [comment]
I have the same error....searching for the solution since a week

Error building Player: CommandInvokationFailure: Failed to re-package resources. See the Console for details.
E:\Softwares\UNITY\Unity\Android\Sdk\build-tools\23.0.2\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "E:/Softwares/UNITY/Unity/Android/Sdk\platforms\android-23\android.jar" -F bin/resources.ap_ --extra-packages android.support.v7.appcompat:com.facebook:com.facebook.android:com.google.android.gms:com.google.unity:com.google.android.gms.ads:com.google.android.gms:android.support.v4 -S "C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res" -S "C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\facebook-android-sdk-4.8.2\res" -S "C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\facebook-android-wrapper-release\res" -S "C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\google-play-services_lib\res" -S "C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\GoogleMobileAdsPlugin\res" -S "C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\play-services-ads-8.4.0\res" -S "C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\play-services-basement-8.4.0\res" -S "C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\support-v4-23.1.1\res"

stderr[
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_alert_dialog_button_bar_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <android.support.v7.widget.ButtonBarLayout>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_alert_dialog_button_bar_material.xml: note: using v17 attributes; synthesizing resource com.rajigare.prgame:layout/abc_alert_dialog_button_bar_material for configuration v17.
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_alert_dialog_material.xml:48: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <android.support.v7.widget.DialogTitle>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_alert_dialog_material.xml: note: using v17 attributes; synthesizing resource com.rajigare.prgame:layout/abc_alert_dialog_material for configuration v17.
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_dialog_title_material.xml:29: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <TextView>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_dialog_title_material.xml: note: using v17 attributes; synthesizing resource com.rajigare.prgame:layout/abc_dialog_title_material for configuration v17.
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_screen_toolbar.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:touchscreenBlocksFocus from <android.support.v7.widget.ActionBarContainer>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_screen_toolbar.xml: note: using v21 attributes; synthesizing resource com.rajigare.prgame:layout/abc_screen_toolbar for configuration v21.
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_search_view.xml:47: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\abc_search_view.xml: note: using v17 attributes; synthesizing resource com.rajigare.prgame:layout/abc_search_view for configuration v17.
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media.xml:42: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media.xml: note: using v17 attributes; synthesizing resource com.rajigare.prgame:layout/notification_template_big_media for configuration v17.
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:60: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <ImageView>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <LinearLayout>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml:30: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentEnd from <include>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_big_media_narrow.xml: note: using v17 attributes; synthesizing resource com.rajigare.prgame:layout/notification_template_big_media_narrow for configuration v17.
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <LinearLayout>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml:77: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml:96: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <TextView>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml:64: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <TextView>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_lines.xml: note: using v17 attributes; synthesizing resource com.rajigare.prgame:layout/notification_template_lines for configuration v17.
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_media.xml:43: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <include>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_media.xml:33: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_media.xml: note: using v17 attributes; synthesizing resource com.rajigare.prgame:layout/notification_template_media for configuration v17.
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_part_chronometer.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <Chronometer>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_part_chronometer.xml: note: using v17 attributes; synthesizing resource com.rajigare.prgame:layout/notification_template_part_chronometer for configuration v17.
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_part_time.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <DateTimeView>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\notification_template_part_time.xml: note: using v17 attributes; synthesizing resource com.rajigare.prgame:layout/notification_template_part_time for configuration v17.
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_powered_by_google.xml:28: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <ImageView>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_powered_by_google.xml:28: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <ImageView>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_powered_by_google.xml:8: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <View>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_powered_by_google.xml: note: using v17 attributes; synthesizing resource com.rajigare.prgame:layout/place_autocomplete_item_powered_by_google for configuration v17.
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_prediction.xml:52: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <TextView>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_prediction.xml:35: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <TextView>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_prediction.xml:8: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentStart from <include>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_item_prediction.xml: note: using v17 attributes; synthesizing resource com.rajigare.prgame:layout/place_autocomplete_item_prediction for configuration v17.
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_progress.xml:2: note: removing attribute http://schemas.android.com/apk/res/android:indeterminateTint from <ProgressBar>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_progress.xml:2: note: removing attribute http://schemas.android.com/apk/res/android:indeterminateTintMode from <ProgressBar>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\google-play-services_lib\res\layout\place_autocomplete_progress.xml: note: using v21 attributes; synthesizing resource com.rajigare.prgame:layout/place_autocomplete_progress for configuration v21.
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <CheckedTextView>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <CheckedTextView>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_multichoice_material.xml: note: using v17 attributes; synthesizing resource com.rajigare.prgame:layout/select_dialog_multichoice_material for configuration v17.
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <CheckedTextView>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <CheckedTextView>
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\appcompat-v7-23.1.1\res\layout\select_dialog_singlechoice_material.xml: note: using v17 attributes; synthesizing resource com.rajigare.prgame:layout/select_dialog_singlechoice_material for configuration v17.
C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\GoogleMobileAdsPlugin\res\values\admob_ads_attrs.xml:10: error: Attribute "adSize" has already been defined

C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\GoogleMobileAdsPlugin\res\values\admob_ads_attrs.xml:17: error: Attribute "adSizes" has already been defined

C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\GoogleMobileAdsPlugin\res\values\admob_ads_attrs.xml:20: error: Attribute "adUnitId" has already been defined

C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\GoogleMobileAdsPlugin\res\values\common_attrs.xml:13: error: Attribute "imageAspectRatioAdjust" has already been defined

C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\GoogleMobileAdsPlugin\res\values\common_attrs.xml:22: error: Attribute "imageAspectRatio" has already been defined

C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\GoogleMobileAdsPlugin\res\values\common_attrs.xml:27: error: Attribute "circleCrop" has already been defined

C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\google-play-services_lib\res\values\admob_ads_attrs.xml:10: error: Attribute "adSize" has already been defined

C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\google-play-services_lib\res\values\admob_ads_attrs.xml:17: error: Attribute "adSizes" has already been defined

C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\google-play-services_lib\res\values\admob_ads_attrs.xml:20: error: Attribute "adUnitId" has already been defined

C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\google-play-services_lib\res\values\base_attrs.xml:11: error: Attribute "buttonSize" has already been defined

C:\Users\PRASMIT\Desktop\pr_fb_ads\Temp\StagingArea\android-libraries\google-play-services_lib\res\values\base_at<message truncated>...

**Comment by rampara** [comment]
It looks like you're trying to add multiple copies of identical Google Play Services to your Unity project. Can you post the contents of your `Assets/Plugins/Android` directory?.

**Comment by ronaldo127** [comment]
Here is the content of mine and I have got the same error:


\Assets\Plugins\Android

06/01/2016  10:46 PM    <DIR>          .
06/01/2016  10:46 PM    <DIR>          ..
06/01/2016  10:41 PM           901,251 appcompat-v7-23.1.1.aar
06/01/2016  10:46 PM               310 appcompat-v7-23.1.1.aar.meta
06/01/2016  10:19 PM            18,647 firebase-common-9.0.1.aar
06/01/2016  10:46 PM               310 firebase-common-9.0.1.aar.meta
06/01/2016  10:29 PM    <DIR>          GoogleMobileAdsPlugin
05/14/2016  03:13 PM               344 GoogleMobileAdsPlugin.meta
06/01/2016  10:19 PM           743,784 play-services-ads-9.0.1.aar
06/01/2016  10:46 PM               310 play-services-ads-9.0.1.aar.meta
06/01/2016  10:19 PM           291,546 play-services-ads-lite-9.0.1.aar
06/01/2016  10:46 PM               310 play-services-ads-lite-9.0.1.aar.meta
06/01/2016  10:19 PM           638,006 play-services-base-9.0.1.aar
06/01/2016  10:46 PM               310 play-services-base-9.0.1.aar.meta
06/01/2016  10:19 PM           565,054 play-services-basement-9.0.1.aar
06/01/2016  10:46 PM               310 play-services-basement-9.0.1.aar.meta
06/01/2016  10:19 PM            20,458 play-services-tasks-9.0.1.aar
06/01/2016  10:46 PM               310 play-services-tasks-9.0.1.aar.meta
06/01/2016  10:41 PM            19,096 support-annotations-23.1.1.jar
06/01/2016  10:46 PM               310 support-annotations-23.1.1.jar.meta
06/01/2016  10:41 PM         1,173,305 support-v4-23.1.1.aar
06/01/2016  10:46 PM               310 support-v4-23.1.1.aar.meta


I've tried to update my sdk but it didn't work for me.

**Comment by akira32** [comment]
I have the same problem.

**Comment by ronaldo127** [comment]
Two useful links:

This I didn't test [https://github.com/googleads/googleads-mobile-unity/issues/210](https://github.com/googleads/googleads-mobile-unity/issues/210)
But [this](https://github.com/googleads/googleads-mobile-unity/issues/221) I did yesterday and worked for me:

**Comment by rampara** [comment]
@ronaldo127 can using the latest version of the plugin (3.0.4) If so, can you delete the AARs in the directory you posted and let background resolution from the JarResolver library run.

**Comment by rampara** [comment]
@ronaldo127 Glad you were able to resolve your issue.
