### ISSUE TITLE
iOS: App Crashes - When running the Unity App on Unity v2018.4.11f1 on iOS 10.

### ISSUE THREAD

**Issue by pm-preety-narvekar** [googleads/googleads-mobile-unity#2254]
### Step 1: Describe your environment

  * Unity version: 2018.4.11f1
  * Google Mobile Ads Unity plugin version: 7.1.0
  * Platform: iOS (iOS, Android, Unity Editor)
  * Platform OS version: iOS 10.3.3 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: All
  * Mediation ad networks used, and their versions: NA

#### Steps to reproduce:

1. Integrate GAM's unity plugin
2. Initialize GAM's banner ad
3. Load banner ad
4. Run the app on iOS 10.3.3 device

#### Actual behaviour
App crashed on launch. Please find attached crash log.
[gam_crashlog.txt](https://github.com/googleads/googleads-mobile-unity/files/9380861/gam_crashlog.txt)

#### Alternative
In xcode project `Always Embed Swift Standard Libraries` is set to `No`, and the app stopped crashing. It sent ad request on load ad but gave below error:
```
AdMob Banner : Ad failed with error - POBError{errorCode=4, errorMessage='Error Domain=com.google.admob Code=4 "Request Error: This device's OS version is below the minimum supported by GMA SDK." UserInfo={NSLocalizedDescription=Request Error: This device's OS version is below the minimum supported by GMA SDK.}'}
AdMobBannerMenu:HandleOnAdFailedToLoad(Object, AdFailedToLoadEventArgs)
```
However, as per the ADMob integration document, it supports iOS 10. Can you please confirm?

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
