### ISSUE TITLE
AdSize Class Missing Few Banner Size

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [googleads/googleads-mobile-unity#2261]
Step 1: Describe your environment

  * Unity version: 2022.1.13f1
  * Google Mobile Ads Unity plugin version: 7.2.0
  * Platform: Unity Editor
  * Platform OS version: Android

Step 2: Describe the problem
AdSize Class Missing Few Banner Size. Like AdSize already have 

public static readonly AdSize Banner = new AdSize(320, 50);
public static readonly AdSize MediumRectangle = new AdSize(300, 250);
public static readonly AdSize IABBanner = new AdSize(468, 60);
public static readonly AdSize Leaderboard = new AdSize(728, 90);

But few other banner sample sizes like Large_Banner, Full_Banner, INVALID, and some others are missing. 
and we have to add their sizes manually in banner constructor.
BannerView bannerView = new BannerView(adUnitId, new AdSize(320,100), AdPosition.TopRight);

Its a suggestion to add these AdSize's by default in GMA unity SDK.

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
