### ISSUE TITLE
Bug in iPhone 14 Pro

### ISSUE THREAD

**Issue by mquaker** [googleads/googleads-mobile-unity#2331]
Unity version: 2021.3.11f1
Google Mobile Ads Unity plugin version: 7.2.0
Platform: IOS
Platform OS version: IOS 16
Any specific devices issue occurs on: iPhone 14 Pro
Mediation ad networks used, and their versions: None

Buttons (mute, close) do not work after interstitial ads are displayed on iPhone 14 Pro.
Although the app is not frozen, there is an issue where the button does not work and the ad cannot be closed.
It works fine on iPhone X or iPhone 12 Pro with the same version of the app.
The OS is all the same IOS16.
Since it is information collected from users after distribution, the log cannot be attached.
Currently, only iPhone 14 users are repeatedly reporting this issue.

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
