### ISSUE TITLE
Rewarded Ads not loading with error: "getMediaUrl is not a function"

### ISSUE THREAD

**Issue by RFEntmt** [googleads/googleads-mobile-unity#2457]
Step 1: Describe your environment

  * Unity version: 2020.3.8f1
  * Google Mobile Ads Unity plugin version: 7.3.1
  * Platform: Android (iOS, Android, Unity Editor)
  * Platform OS version: Android 10 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: Xiaomi Mi 8 PRO
  * Mediation ad networks used, and their versions: Unity Ads

Step 2: I was updating all my projects sdk's to resolve a problem and was blessed with this new one, I'm not able to load rewarded ads anymore, getting the following error:
```
2022/12/15 23:52:43.427 27985 27985 Error Ads JS: Uncaught (in promise) TypeError: KA(...).getMediaUrl is not a function (https://imasdk.googleapis.com/admob/sdkloader/production/rewarded_adx_video_v1_en.js:798)
2022/12/15 23:52:43.447 27985 28202 Error cr_MediaCodecUtil Decoder for type video/av01 is not supported on this device [requireSoftware=false, requireHardware=true].
```

![image](https://user-images.githubusercontent.com/39604165/208013320-c683f092-3fab-4c13-8bbe-d7360166dd3b.png)

**Comment by AiorosRa94** [comment]
Could you solve?

**Comment by NVentimiglia** [comment]
Hi @AiorosRa94 

I will need more details to know how the Admob plugin is responsible. Please open a[ fourm case](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines) and include a full stack trace of this error and any additional details such as your publisher Id, affected ad units, and mediation setup.

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
