### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by IndieKApi** [googleads/googleads-mobile-unity#2474]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.8.f1
  * Google Mobile Ads Unity plugin version: Google Mobile Ads Unity Plugin v7.3.1
  * Platform: Android 
  * Platform OS version: Android 9
  * Any specific devices issue occurs on: NIL
  * Mediation ad networks used, and their versions:NIL

![Screenshot (12)](https://user-images.githubusercontent.com/114830150/211318589-858854bd-c566-4181-8e70-69c3a64d9b01.png)

Getting this error :(

**Comment by NVentimiglia** [comment]
Hi @IndieKApi 

This is a new error to me. 

1. Can you try running the Assets > Dependency Manager > Android Resolver > Force Resolve command.
2. Can you please include any logs associated with this error.

Looking forward to your reply

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
