### ISSUE TITLE
Google Mobile Ads SDK - must be higher than Version 6.4.1 

### ISSUE THREAD

**Issue by mole84** [googleads/googleads-mobile-unity#248]
hi, google admob works after 15. september 2016 just with higher versions than Google Mobile Ads SDK Version 6.4.1

- what about this plugin (v. 2.2.1), will it still work?
- how and where can i check my version of the Google Mobile Ads SDK ?

**Comment by rampara** [comment]
It is always recommended to use the latest version of the Unity plugin to take advantage of bug fixes and additional features. Older versions of the plugin are not tested to check for compatibility with the current Google Mobile Ads SDKs. You can check the installed version of Google Play services on your computer through the SDK Manager.

**Comment by ChaserKnight** [comment]
I am using v3.0.2 of this Unity plugin, will my ads still display after 15 Sep? Please reply.

**Comment by ericleich** [comment]
If you are using v1.2 or higher of the Unity plugin, you are fine.

Also, the note you may have gotten about SDK needing to be higher than v6.4.1 refers to a legacy, standalone Mobile Ads SDK that was [deprecated back in February 2014](http://googleadsdeveloper.blogspot.com/2014/02/since-joining-google-play-services-back.html), and that had it's own versioning system. That deprecation does **NOT** refer at all to the use of Google Play services. What that means is even if you are using Google Play services 4.0 which was [released back in October 2013](https://firebase.google.com/docs/admob/release-notes), you are still ok.

Having said all that, what @rampara said is still good advice. Updating to the latest versions of the SDK and Unity plugin is highly recommended. If you report issues with super old libraries, the first thing we'll ask you is to try it on the latest version and see if it's still a problem.
