### ISSUE TITLE
Adsize.Leaderboard dont work

### ISSUE THREAD

**Issue by ede21** [googleads/googleads-mobile-unity#258]
Hi,

tested the plugin with unity and plays with the sizes of the banner. If i choose Adsize.Leaderboard no ad is showing. 
Furthermore i read the Google API and i saw there are more sizes possible (https://developers.google.com/android/reference/com/google/android/gms/ads/AdSize). Why is this not in the plugin?

regards

**Comment by rampara** [comment]
I'm able to request and display leaderboard test ads without issue. It's important to note that due to the size of leaderboard ads, they can only be requested from tablets or other large screen devices.  If you're still having difficulty requesting and displaying leaderboard ads on a tablet, can you post the logcat output under the "Ads" tag generated during an ad request.

**Comment by rampara** [comment]
Closing this issue due to it's age and non-response. If this issue persists for you, please re-open the issue.
