### ISSUE TITLE
Errors in build with Unity IOS plugin v3.1.0

### ISSUE THREAD

**Issue by iv777** [googleads/googleads-mobile-unity#284]
Hello!

I have Unity 5.4.1p3 on the Windows.
Google Mobile Ads Unity Plugin v3.1.0
I created empty project and imported the plugin.
When I try to build for IOS - I have errors:

'pod' command not found; unable to generate a usable Xcode project. You can install cocoapods with the Ruby gem package manager:

> sudo gem install -n /usr/local/bin cocoapods
> pod setup
> UnityEngine.Debug:LogError(Object)
> Google.IOSResolver:Log(String, Boolean, LogLevel)
> Google.IOSResolver:OnPostProcessInstallPods(BuildTarget, String)
> UnityEditor.HostView:OnGUI()

Unknown file extension: .xml
UnityEditor.HostView:OnGUI()

Unknown file extension: .meta
UnityEditor.HostView:OnGUI()

Unknown file extension: .jar
UnityEditor.HostView:OnGUI()

I work in the Windows so I cant do any "sudo" commands.

**Comment by rampara** [comment]
It is my understanding that Unity does not support building iOS projects on Windows machines. Were you able to build on deploy your Unity project to iOS when not using this plugin?

**Comment by iv777** [comment]
Unity for Windows have ability to build xcode iOS projects.
But I understood - this plugin use the CocoaPods which can be used only on the Mac.

**Comment by rampara** [comment]
The [JarResolver](https://github.com/googlesamples/unity-jar-resolver) library that this plugin uses to resolve Google Mobile Ads iOS SDK dependencies relies on Cocoapods. Since Cocoapods is unavailable for the Windows platform, you will have to turn off automatic dependency resolution and manually include the GMA iOS SDK in your Unity project. To do so, follow the steps listed below:

1. Build the latest version of this plugin (which will pull in the latest version of the JarResolver library) by executing the Gradle build script in the root directory of this repo. The script can by simply executing Grade without any arguments: `./gradle`
2. Import the the Unity package generated in Step 1 into your Unity project.
3. Turn off automatic dependency resolution by navigating to `Assets -> Play Services Resolver -> iOS Resolver -> Settings` and unselecting `Podfile Generation`.
3. Manually include the GMA iOS framework in your Unity project by copying the framework (available for download [here](https://firebase.google.com/docs/admob/ios/download)) to the `Assets/Plugins/iOS` directory of your Unity project.

**Comment by rampara** [comment]
Closing this issue due to its age. Please re-open if this issue persists for you.
