### ISSUE TITLE
External Dependency Manager fails to resolve the MetaAudienceNetwork dependencies.

### ISSUE THREAD

**Issue by Davidnovarro** [googleads/googleads-mobile-unity#2943]
* Unity version: 2022.3.10f1
  * Google Mobile Ads Unity plugin version: v8.5.2
  * Platform: UnityEditor Android build
  * Mediation ad networks used, and their versions: IronSource-2.3.1, UnityAds-3.8.0, AppLovin-6.9.1, MetaAudienceNetwork-3.11.0

Apparently when I add MetaAudienceNetwork-3.11.0 adapter External Dependency Manager fails to resolve.
Here is the console error message:
```
Resolution failed
Failed to fetch the following dependencies:
org.jetbrains.kotlin:kotlin-bom:1.8.10
```

#### Steps to reproduce:
Download the demo project
[https://drive.google.com/file/d/1raDeZt11w3lO7tl8L-OHIi1TWwYlfoUq](https://drive.google.com/file/d/1raDeZt11w3lO7tl8L-OHIi1TWwYlfoUq)
Try to resolve the dependencies:
Assets > External Dependency Resolver > Android Resolver > Force Resolve

**Comment by dcosmin-97** [comment]
Hello!
This issue is related to Unity. 
Please check here: https://github.com/googleads/googleads-mobile-unity/issues/2925

**Comment by luizjunior** [comment]
same problem here with Meta Mediation Adapter [Version 3.11.0]

**Comment by NVentimiglia** [comment]
Thank you for the awareness, we are looking into the issue.

b/300314212

**Comment by nealohb** [comment]
Same problem for me, using identical mediation setup as luizjunior. Meta is the culprit - removing it and everything works fine.

Also for whatever reason when Meta is involved there are depency conflicts which causes a lot of depencies to get bumped to use the latest version (resulting in downloading versions that are not officially supported). For me it looks like this:

Some conflicting dependencies were found.
The following dependency versions were modified:
com.google.ads.mediation:applovin:11.10.1.0 --> com.google.ads.mediation:applovin:11.+
com.google.ads.mediation:facebook:6.15.0.0 --> com.google.ads.mediation:facebook:6.+
com.google.ads.mediation:unity:4.8.0.0 --> com.google.ads.mediation:unity:4.+
com.google.android.gms:play-services-ads:22.3.0 --> com.google.android.gms:play-services-ads:+
com.google.android.gms:play-services-auth:20.4.1+ --> com.google.android.gms:play-services-auth:+
com.google.android.gms:play-services-base:18.2.0 --> com.google.android.gms:play-services-base:+
com.google.android.gms:play-services-games:23.1.0+ --> com.google.android.gms:play-services-games:+
com.google.android.gms:play-services-nearby:17.0.0+ --> com.google.android.gms:play-services-nearby:+
com.google.android.play:review:2.0.1+ --> com.google.android.play:review:+
com.google.android.ump:user-messaging-platform:2.1.0 --> com.google.android.ump:user-messaging-platform:+
com.google.firebase:firebase-analytics:21.3.0 --> com.google.firebase:firebase-analytics:+
com.google.firebase:firebase-auth:22.1.1 --> com.google.firebase:firebase-auth:+
com.google.firebase:firebase-common:20.3.3 --> com.google.firebase:firebase-common:+
com.google.firebase:firebase-config:21.4.1 --> com.google.firebase:firebase-config:+
com.google.firebase:firebase-database:20.2.2 --> com.google.firebase:firebase-database:+
com.google.firebase:firebase-functions:20.3.1 --> com.google.firebase:firebase-functions:+
com.unity3d.ads:unity-ads:4.8.0 --> com.unity3d.ads:unity-ads:+

**Comment by nixonok** [comment]
So, for a month I'm having build issues with Meta Audience Network mediation via AdMob

To recreate you just open any new unity project under any unity version, download Google Ads Mobile SDK, resolve then add Meta Audience Network unity package from mediation page, resolve, the resolve will take a long time attempting to resolve and then timeout on few, the build will result in workers$actionfacade

Since meta mediation is important for me, i tried to go to previous versions where the build was fine but the build still failed, then i went to  Meta Audience Network Unity Mediation Plugin Changelog and tried every single new and previous version mentioned as built and tested there, with this same result once the mediation plugin is added

Without the meta plugin everything's fine, 

I looked a bit further, the EDM's resolution attempts fails and it attempts to resolve 15 times, that's what makes the resolution take so much time, seems like some dependency of meta is not available in their links.

This issue i think is from meta somehow, Meta is a very important mediation for us since we get around 40% or revenue from meta, since this issue is so wide spread, i hope the team will take this as their first priority and come up with a fix fast.

Thanks in advance.

**Comment by NVentimiglia** [comment]
Hi Everyone,

We are aware of the issue and are currently looking into a fix.

**Comment by RomainBitard** [comment]
> Hi Everyone,
> 
> We are aware of the issue and are currently looking into a fix.

is there a workaround ? I'm having the same issue but I don't know if it's from meta or another adapter

**Comment by RomainBitard** [comment]
@NVentimiglia irrelevant question but everytime I upgrade the SDK there are adapter and all bugs. 
Why don't the team test each release with each latest adapters ? That sounds logical to me. When you read the doc, unity is tested with X, meta with Y, and so on, it's so odd and unpractical

**Comment by nixonok** [comment]
Any workaround/update on this yet? since this issue is so widespread, no version of the admob unity plugin is getting an Android build with meta mediation, shouldn't it be a p1? any eta at least?

**Comment by dcosmin-97** [comment]
I have tried with Unity 2022 and it still does not work.

**Comment by NVentimiglia** [comment]
This is a known issue and we are working on a fix.

As a work around you can hard code the maximum version of the google mobile ads Android sdk in the `GoogleMobileAdsDependencies.xml` file.

```
<dependencies>
  <androidPackages>
    <androidPackage spec="com.google.android.gms:play-services-ads:[22.3.0]">
      <repositories>
        <repository>https://maven.google.com/</repository>
      </repositories>
    </androidPackage>
  </androidPackages>

  <iosPods>
    <iosPod name="Google-Mobile-Ads-SDK" version="~> 10.9">
      <sources>
        <source>https://github.com/CocoaPods/Specs</source>
      </sources>
    </iosPod>
  </iosPods>
</dependencies>
```

**Comment by Raydekk** [comment]
Workaround does not work for me - same thing happens. 
Is there a certain version that needs to be used here: com.google.android.gms:play-services-ads ?

I'm on Unity 2021.3.31 with Google Mobile Ads Unity plugin 8.5.2

**Comment by NVentimiglia** [comment]
@Raydekk 

You can also try updating to Unity `2022.3`.

> Is there a certain version that needs to be used here: com.google.android.gms:play-services-ads ?

The issue is specific to Android version `22.4.0`

The Google Mobile Ads Android SDK 22.4.0 added a [<property>](https://developer.android.com/guide/topics/manifest/property-element) element in its Android manifest. Building against this version or higher requires Android compile API level 33 or higher, Gradle 6.7.1 or higher, and [Android Gradle plugin](https://developer.android.com/reference/tools/gradle-api) 4.2.0 or higher.


We are looking into a better fix.

**Comment by RomainBitard** [comment]
> We are looking into a better fix.

Thanks a lot, will the release process be improved ? Each time I upgrade there are issues, that'd be good if the adapters where tested too

**Comment by NVentimiglia** [comment]
@RomainBitard 

Yes, we are working on a better fix.

**Comment by NVentimiglia** [comment]
We have posted a blog detailing a work around for this issue
https://developers.google.com/admob/unity/gradle

Please reopen this bug if you face further difficulties.
