### ISSUE TITLE
Google.JarResolver.PlayServicesSupport & Google.JarResolver.Dependency defined multiple times

### ISSUE THREAD

**Issue by siddharth3322** [googleads/googleads-mobile-unity#306]
As per my title suggest, I was getting above error when I import last plugin of AdMob unity plugin.

Here is screenshot that represent this error.

![screen shot 2016-11-15 at 12 04 00 am](https://cloud.githubusercontent.com/assets/3082151/20277562/14068aba-aac7-11e6-9e3b-9f461ea23bf2.png)

Please give some proper solution for this thing, rather than doing few experiments.
Because I already read other thread of similar error as well.

**Comment by rampara** [comment]
Delete the contents of the `Assets/PlayServicesResolver` directory within your Unity project and re-import the latest version of the Google Mobile Ads plugin.

**Comment by kgooble** [comment]
Hi, I got the same error as the original poster. However, when I tried deleting the contents of `Assets/PlayServicesResolver` and then importing the Google Mobile Ads Plugin, I got this error instead:

![screen shot 2016-11-29 at 1 49 20 pm](https://cloud.githubusercontent.com/assets/3249141/20724035/c5c40cf4-b63a-11e6-978b-cc90eb35ea50.png)

**Comment by rampara** [comment]
@kgooble are you using the latest version of this plugin?

**Comment by kgooble** [comment]
@rampara Yep, I downloaded version 3.1.2 of the unitypackage from https://github.com/googleads/googleads-mobile-unity/releases. I'm using version 0.9.32 of the GooglePlayGames plugin.

**Comment by rampara** [comment]
In the latest version of the plugin, the file for which you're receiving an error should not be present (it's been compiled into dll).

**Comment by kgooble** [comment]
Hey, I ended up fixing the issue! I upgraded my Google Play Games plugin to 0.9.35, but I also had to do a few more steps:

- I added a `version.xml` file under `Assets/Plugins/Android/GoogleMobileAdsPlugin/res/values/version.xml` because otherwise I would get errors asking about the `google_play_services_version` not being found
- I added a `values.xml` file under `Assets/Plugins/Android/GoogleMobileAdsPlugin/res/values/values.xml` because otherwise I would get errors about `@style/Theme.IAPTheme` not being found
- I added `multiDexEnabled true` to the gradle file for our project

The XML files were retrieved from within one of the AAR files added to the project, for some reason when building it could not figure out where these values were defined so I manually added them into the project. I unzipped all the AAR files that were included with the Admob plugin and grepped for the values mentioned in the errors and used the file that had the value. After that, the Android build worked. However, running the game crashed, so I ended up having to change the version value in the `version.xml` file to `10084000`.

Thanks for your help!

**Comment by rampara** [comment]
I'm glad you were able to resolve your issue but those additional steps shouldn't be necessary. I'm able to integrate both the Google Mobile Ads and Google Play Games Unity plugins into the [sample application](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld) included in this repo with the following steps:

1. Import latest version of Google Mobile Ads Unity plugin (v3.1.3)
2. Import latest version of Google Play Games plugin (v0.3.5)
3. Build Android APK. 

With just the steps above I'm able to build an Android APK without issues.
