### ISSUE TITLE
GoogleMobileAds.Ump.Android.ConsentFormClient..ctor

### ISSUE THREAD

**Issue by hieulvsupga** [googleads/googleads-mobile-unity#3093]
Environment
-Unity version: 2021.3.15f1
-Google Mobile Ads Unity plugin version: 8.5.3
-Platform: Android
-Mediation ad networks used, and their versions: Unity, Meta
Describe the problem:
-After making the game public, firebase sent me this notification " Non-fatal Exception: java.lang.Exception
AndroidJavaException : java.lang.ClassNotFoundException: com.google.unity.ump.UnityConsentFormCallback
![e](https://github.com/googleads/googleads-mobile-unity/assets/143372667/26908e09-619d-4d67-9341-911aba0c98b8)
"

**Comment by NVentimiglia** [comment]
Hi @hieulvsupga 

The `java.lang.ClassNotFoundException` usually happens when the UMP `.arr` dependency is not included in the build. This sometimes happens when the `External Dependency Manager` fails to resolve and we did not configure the gradle manifest.

Can you please confirm that the dependencies are included in the build. 

Let me know if you need assisstance,
Nick
