### ISSUE TITLE
Admob Interstitial Error

### ISSUE THREAD

**Issue by sezbladex** [googleads/googleads-mobile-unity#310]
I import unitypackage i look events interstitial ad loaded event recieved but i touch show, Interstitial ad not ready yet. i am waiting  again same error i use your example script to my game

**Comment by rampara** [comment]
If I understand correctly, the issue you are experiencing is after loading an interstitial and receiving an OnAdLoaded event, attempting to show the interstitial results in a warning that interstitial is not ready yet. Is this correct? If so, on which platform are you seeing this issue? Also, can you confirm that the issue is reproducible with the sample application included in this repo?

**Comment by sezbladex** [comment]
@rampara  I fixed problem thanks

**Comment by rampara** [comment]
Glad you were able to get your issue resolved.
