### ISSUE TITLE
[Huge ANR Spike] [:com.google.android.gms.policy_ads_fdr_dynamite] [input dispatching timeout]

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [googleads/googleads-mobile-unity#3227]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.3.23f1
  * Google Mobile Ads Unity plugin version: 8.6.0, 8.7.0
  * Platform: Android
  * Mediation ad networks used, and their versions: Applovin(7.0.0, 7.0.1), Liftoff(4.0.0), Meta(3.11.0), Mintegral(1.3.0, 1.4.0) (mediation also not matter same ANRs occurring without mediation)

### [REQUIRED] Step 2: Describe the problem
After upgrading from 8.2.0 to 8.6.0 and 8.7.0 seeing hug ANRs spike in all my games. worst part is that play console adding our games in bad behaviour.
My ANRs rating is gone upto 8% from 0.1-0.4.

![PlayConsole](https://github.com/googleads/googleads-mobile-unity/assets/32755091/f2040a81-eec2-4c63-9af6-9223141ebded)
![Firebase_ANR_detail](https://github.com/googleads/googleads-mobile-unity/assets/32755091/3738fdff-ec5c-48ab-a052-0b771693902e)
[ANR stacktrace.log](https://github.com/googleads/googleads-mobile-unity/files/14635332/ANR.stacktrace.log)

[issue_13a464d1d86ca2213f481fbf301a682b_ANR_session_65F1C74C03B200015BDDB2600D636631_DNE_0_v2_stacktrace.txt](https://github.com/googleads/googleads-mobile-unity/files/14635333/issue_13a464d1d86ca2213f481fbf301a682b_ANR_session_65F1C74C03B200015BDDB2600D636631_DNE_0_v2_stacktrace.txt)

**Comment by MuhammadWaqasOfficial** [comment]
Another game data
![image_2024_03_18T17_10_04_063Z](https://github.com/googleads/googleads-mobile-unity/assets/32755091/4a503d33-7917-4b7d-ab2f-be13b3e9b51f)
![IMG_20240318_222426](https://github.com/googleads/googleads-mobile-unity/assets/32755091/cf3b5a4d-a4e4-430b-b876-2b716b6fdbdb)
![IMG_20240318_222530](https://github.com/googleads/googleads-mobile-unity/assets/32755091/2630d5d1-65fc-4ef9-b0b4-75e34a2f07ae)
[stacktrace other game.log](https://github.com/googleads/googleads-mobile-unity/files/14640264/stacktrace.other.game.log)

**Comment by NVentimiglia** [comment]
@MuhammadWaqasOfficial 

This issue is outside of the scope of the Unity plugin. Please reach out to the [Android Team](https://developers.google.com/admob/support) for help here. Please link this github issue as it is a great explanation.

**Comment by phamhung99** [comment]
I am using GMA 9.0.0, when I update firebase from 10.3 to 11.9, ANR :com.google.android.gms.policy_ads_fdr_dynamite@241806205@241806202034.633974825.633974825 - m.amn.bh
 appear. Does anyone knonw about this?

**Comment by MuhammadWaqasOfficial** [comment]
> I am using GMA 9.0.0, when I update firebase from 10.3 to 11.9, ANR :com.google.android.gms.policy_ads_fdr_dynamite@241806205@241806202034.633974825.633974825 - m.amn.bh appear. Does anyone knonw about this?

no, did you implement admob according to the latest [admob documentation](https://developers.google.com/admob/unity/quick-start) or old one?

**Comment by MCISMc** [comment]
Issue Report for Google AdMob - Unity Game Crash
Subject: Unity Game Crash Due to Google Mobile Ads Blocking Main Thread

Description:
We are experiencing a major crash in our Unity-based mobile game (Fighter Pilot: CAS A-10) caused by Google Mobile Ads SDK blocking the main thread. The issue occurs in Google Play Services Ads (com.google.android.gms.policy_ads_fdr_dynamite), causing the main thread to freeze, followed by a Unity native crash in libunity.so.

Crash Details:
Game: Fighter Pilot:Heavy Fire
Unity Version: 2022.3.55f1 (LTS)
Google Mobile Ads SDK Version: [9.6.0]
Platform: Android
OS Version: Affects multiple Android versions (including Android 14)
Device Models: Various
Stack Trace (Relevant Parts):
Main Thread Blocked:

php
Copy
Edit
"main" tid=1 Blocked
  at m.avs.handleMessage (:com.google.android.gms.policy_ads_fdr_dynamite)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at m.bbd.a (:com.google.android.gms.policy_ads_fdr_dynamite)
  at m.bbd.dispatchMessage (:com.google.android.gms.policy_ads_fdr_dynamite)
  at android.os.Looper.loopOnce (Looper.java:233)
  at android.os.Looper.loop (Looper.java:344)
  at android.app.ActivityThread.main (ActivityThread.java:8249)
Unity Native Crash:

java
Copy
Edit
"UnityMain" tid=39 Native
  at jni::LocalScope::LocalScope()
  at DisplayListenerAvailable()
  at ScreenManagerAndroid::SetRequestedResolution()
  at ExecutePlayerLoop(NativePlayerLoopSystem*)
  at UnityPlayerLoop()
  at nativeRender(_JNIEnv*, _jobject*)
  at com.unity3d.player.UnityPlayer.nativeRender (Native method)
Issue Details & Observations:
Google Mobile Ads SDK is correctly initialized

We have enabled Optimize Initialization and Ad Loading.
Initialization completes successfully before requesting ads.
Main Thread Blocked in Play Services Ads Module

The crash occurs after an ad request.
The handleMessage() function in policy_ads_fdr_dynamite freezes the main thread.
Unity Display API Failure (Possible Conflict with AdMob)

ScreenManagerAndroid::SetRequestedResolution() crashes after the ad system blocks the main thread.
This may indicate a race condition between ad rendering and Unity's display system.
Steps to Reproduce:
Launch the game on an Android device.
Wait for the ad to load and display.
Game freezes, followed by a native crash.
What We Have Tried:
✅ Ensured correct SDK initialization (Optimize Initialization + Ad Loading).
✅ Updated Google Mobile Ads SDK to the latest version 9.6.0.
✅ Updated Unity to LTS version (2022.3.55f1).
✅ Tested on multiple devices and OS versions.
✅ Disabled ad loading and confirmed the crash does not happen.

Expected Behavior:
The game should not freeze or crash when loading or displaying ads.

Request for Assistance:
Is this a known issue with the latest Google Mobile Ads SDK?
Could there be a threading issue when handling ad events?
Any recommended fixes or workarounds to prevent the main thread from blocking?

I have attached the stack trace log for more info.

[stacktrace.log](https://github.com/user-attachments/files/19386391/stacktrace.log)
