### ISSUE TITLE
Rewarded Video Frequency Capping don't work

### ISSUE THREAD

**Issue by technohowl** [googleads/googleads-mobile-unity#335]
Frequency capping do not work for rewarded videos. (I have not tested the interstitials.)

I have setup 2 impressions per hour for rewarded video ad unit. Even then I am able to load and show rewarded video.

**Comment by ericleich** [comment]
There is an open bug that's being investigated internally with frequency capping in AdMob. Note that the problem and eventual fix will be at the ad serving level, which means it won't require a Unity plugin update, nor a Google Mobile Ads SDK update, once the fix happens.

I'm closing this issue since there's nothing the Unity plugin can do here.

**Comment by ericleich** [comment]
A fix for the open bug I was talking about earlier has just been rolled out. Feel free to try it again.
