### ISSUE TITLE
Banner Ad positioning not working on iOS.

### ISSUE THREAD

**Issue by NVentimiglia** [googleads/googleads-mobile-unity#3455]
We also faced the same issue when installing google ads mobile version 9.1.0 and Unity 2023.2.3f1 
In the app, we put banner ads at the bottom of the screen but when running on IOS device, banner ads are pushed to the top. 
_This does not happen on Editor and Android_
![image](https://github.com/user-attachments/assets/e4eaca8e-9f4a-4d50-8a02-49706cd1a319)
![image](https://github.com/user-attachments/assets/14e5a034-1651-4e34-abd5-e498ebbb1a57)

_Originally posted by @Baonguyen-devg in https://github.com/googleads/googleads-mobile-unity/issues/3369#issuecomment-2232821935_

**Comment by Baonguyen-devg** [comment]
Thank you for your attention and feedback on our issue.

After removing the old package version and installing the latest version, our previous problem has improved; the banner is no longer pushed to the top. However, it still appears to be slightly pushed up when the AdPosition is set to bottom, not fully at the bottom of the device. This also happens when we run it on different iOS devices.

We suspect that this may be related to the default navigation bar at the bottom of iOS devices or notch, as there have been similar cases in the past. Has Google AdMob provided a solution for this issue?

![image](https://github.com/user-attachments/assets/c3c7b91d-9658-40b8-b530-f1da8b543314)
