### ISSUE TITLE
Ios Build Error

### ISSUE THREAD

**Issue by gokhanci** [googleads/googleads-mobile-unity#350]
Win32Exception: ApplicationName='gem', CommandLine='environment', CurrentDirectory='C:\Users\Gokhan\Desktop\Games\JU-PU'
System.Diagnostics.Process.Start_noshell (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start ()
(wrapper remoting-invoke-with-check) System.Diagnostics.Process:Start ()

**Comment by rampara** [comment]
Can you elaborate on this error? Is this output you see in the Unity console when trying to create and iOS build? What version of Unity and plugin are you using? What OS is the development machine you are attempting to build on?

**Comment by azharyounus** [comment]
I got the same error in console when building game for iOS. Unity version is 5.5.0. building game on windows 8 machine.

**Comment by DEKAGATO** [comment]
I  got same this error with unity 5.5 and admob ver 3.3.0. my project was added googlemobileadssdkios

**Comment by rampara** [comment]
The [JarResolver](https://github.com/googlesamples/unity-jar-resolver) library that this plugin uses to resolve Google Mobile Ads iOS SDK dependencies relies on Cocoapods. Since Cocoapods is unavailable for the Windows platform, you will have to turn off automatic dependency resolution and manually include the GMA iOS SDK in your Unity project. To do so, follow the steps listed below:

1. Build the latest version of this plugin (which will pull in the latest version of the JarResolver library) by executing the Gradle build script in the root directory of this repo. The script can by simply executing Grade without any arguments: `./gradle`
2. Import the the Unity package generated in Step 1 into your Unity project.
3. Turn off automatic dependency resolution by navigating to `Assets -> Play Services Resolver -> iOS Resolver -> Settings` and unselecting `Podfile Generation`.
3. Manually include the GMA iOS framework in your Unity project by copying the framework (available for download [here](https://firebase.google.com/docs/admob/ios/download)) to the `Assets/Plugins/iOS` directory of your Unity project.

**Comment by rampara** [comment]
Closing this issue due to non-response. Please re-open if this issue persists for you.
