### ISSUE TITLE
The interstitial ad on the ios device is displayed only once

### ISSUE THREAD

**Issue by cocosUnity** [googleads/googleads-mobile-unity#357]
With the same item, the Interstitial on the Android device are displayed properly, and the ios device only shows once.

**Comment by rampara** [comment]
In the iOS GMA SDK, `GADInterstitial` is a one time use object. Since the Google Mobile Ads Unity plugin is a wrapper for the Google Mobile Ads Unity SDK, the same limitations apply. You can find more information on our [developer docs](https://firebase.google.com/docs/admob/ios/interstitial#only_show_gadinterstitial_once). Every time you make a interstitial ad request, you should use a new interstitial object. Our sample project (included in this repo) is a good example for what best practice should be.
