### ISSUE TITLE
Can't resolve dependencies with new GMA 9.4.0

### ISSUE THREAD

**Issue by madTeddy** [googleads/googleads-mobile-unity#3692]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.52f1
  * Google Mobile Ads Unity plugin version: 9.4.0
  * Plugin installation method: .unitypackage (Unity package manager, .unitypackage import)
  * Platform: Android (iOS, Android, Unity Editor)
  * Mediation ad networks used, and their versions: Applovin 8.0.2

#### Steps to reproduce:

When trying to get dependencies via External Dependency Manager, I see an error:
```
Execution failed for task ':process_androidx.annotation.annotation-experimental-1.4.0.aar'.
> Unsupported class file major version 61
```

With GMA 9.3.0 I don't have this problem.

**Comment by vinkini** [comment]
Hello,

The unsupported class file is due to mismatch in the Java version used by the Unity Editor and the the Java version used to compile the annotation-experimental-1.4.0.aar binary. I was able to resolve this on my end by letting Gradle do the dependency management instead of External Dependency Manager. Here are ths steps I followed:
1. Turn on "Patch mainTemplate.gradle" in Assets > External Dependency Manager > Android Resolver > Settings
![image](https://github.com/user-attachments/assets/3a12e5b1-8657-4d22-8ba8-d9d832fbf6fd)
2. Delete Previously downloaded libraries. Assets > External Dependency Manager > Android Resolver > Delete Resolved Libraries. [If this doesn't end up deleting all the resolved libraries in Assets > Plugins > Android, then you might have to manually delete the libraries].
3. Assets > External Dependency Manager > Android Resolver >  Force Resolve. This step now shouldnt pull any of the libraries but insteads fixes the gradle files to include the necessary libraries. Gradle does the dependency management henceforth. 

Let us know if this works for you. In the mean time we will investigate what changed to cause this issue to pop up in 9.4.0 and not in the version before.

**Comment by madTeddy** [comment]
> Hello,
> 
> The unsupported class file is due to mismatch in the Java version used by the Unity Editor and the the Java version used to compile the annotation-experimental-1.4.0.aar binary. I was able to resolve this on my end by letting Gradle do the dependency management instead of External Dependency Manager. Here are ths steps I followed:
> 
> 1. Turn on "Patch mainTemplate.gradle" in Assets > External Dependency Manager > Android Resolver > Settings
>    ![image](https://private-user-images.githubusercontent.com/124566788/387006046-3a12e5b1-8657-4d22-8ba8-d9d832fbf6fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NzkxNjUsIm5iZiI6MTczMTg3ODg2NSwicGF0aCI6Ii8xMjQ1NjY3ODgvMzg3MDA2MDQ2LTNhMTJlNWIxLTg2NTctNGQyMi04YmE4LWQ5ZDgzMmZiZjZmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QyMTI3NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmZiMzNhNDY0Y2E4NDhlZDg5NDdiNzQ5MWYwODRhODc1M2IxNjhhMjg3YmM3NmQ2OTlhYjg5NjBmNGZiODYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aLL97w0F2HyP67rX6l5C8fuCQew-o5Qv_xFOsleI7lU)
> 2. Delete Previously downloaded libraries. Assets > External Dependency Manager > Android Resolver > Delete Resolved Libraries. [If this doesn't end up deleting all the resolved libraries in Assets > Plugins > Android, then you might have to manually delete the libraries].
> 3. Assets > External Dependency Manager > Android Resolver >  Force Resolve. This step now shouldnt pull any of the libraries but insteads fixes the gradle files to include the necessary libraries. Gradle does the dependency management henceforth.
> 
> Let us know if this works for you. In the mean time we will investigate what changed to cause this issue to pop up in 9.4.0 and not in the version before.

I turned off **Patch mainTemplate.gradle**, because with it, I can't build a project with the **Google Play Games v11** plugin... So I guess if this is the only solution, I will stay on version 9.3.0 for now.

**Comment by vinkini** [comment]
Thanks for letting us know. We will take a look into it. In the mean time 9.3.0 sounds good. If you need to upgrade the underlying Android and iOS SDKs you can manually update the Assets > GoogleMobileAds > Editor > GoogleMobileAdsDependencies.xml file to point to 11.12 for iOS and 23.5.0 for Android.
