### ISSUE TITLE
Hello Rampara, For Interstitial admob ads and Rewarded Video not coming for IOS while integration from unity Side.

### ISSUE THREAD

**Issue by ravi2831** [googleads/googleads-mobile-unity#525]
Hello Rampara, For Interstitial admob ads and Rewarded Video not coming for IOS while integration from unity Side.Mediation ads coming but Not Admob .Interstitial admob ads and Rewarded Video Mediation like AdColony,MoVista,Unity etc all coming except Admob. i given more priority to Admob but Admob not coming. For testing i removed Other mediation also but Admob not coming . only one or 2 times i got Admob ads.I have tested with this new Package and last package. Same Issues .

For Android it's coming.No any Issues. only issues for IOS.

"Interstitial is not ready yet" Coming

**Comment by ravi2831** [comment]
Now i'm using new GoogleMobileAds SDK . Now Admob Ads frequency more. But only SomeTimes.

**Comment by rampara** [comment]
@ravi2831 are running into this issue with a published app? If not, you can try setting your device as a test device. As this issue is not pertaining to a bug in this plugin or a feature request, I'm closing this issue. For support issues you can reach out on the [Google Mobile Ads Technical Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk).
