### ISSUE TITLE
Windows exporting to iOS possible?

### ISSUE THREAD

**Issue by xxPillsxx** [googleads/googleads-mobile-unity#534]
Right now I'm working on a mobile game on my PC. I got AdMob working correctly with ads functioning and all, on Android. Obviously the next step was exporting to iOS. I use my PC to develop since it's faster and then export and paste the xcode project to my MacBook Air to deploy it to my devices. However, when I try to deploy it, the project builds successfully, but the linking process returns lots of errors.
![capture](https://user-images.githubusercontent.com/1680830/31370801-bd47d6d0-adb7-11e7-8cfd-9046bf7ce1c3.PNG)
I did include the framework and using the latest SDK (3.7.1)
I've googled a bit and saw some mentions about Cocoapods, but when I use iOS Resolver > Install Cocoapods, nothing happens. Unity also does not generate xcworkspace or anything. Does this mean I have to use my MacBook for it to work?

**Comment by rampara** [comment]
@xxPillsxx iOS Resolve will not work on windows as it uses Cocoapods. You will have to manually include the [Google Mobile Ads iOS SDK](https://developers.google.com/admob/ios/download) in the `Assets/Plugins/iOS` of your Unity project. As this issue is not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
