### ISSUE TITLE
Reward Ad Close and Reward Event Callbacks Not Called

### ISSUE THREAD

**Issue by sagar7029** [googleads/googleads-mobile-unity#541]
After watching rewarded videos , Reward Ad Close and Reward Event Callbacks are not called.
Debug are also not calling..
Can u Guide How To Call in IOS Unity Plugin.

**Comment by rsodre** [comment]
Are you initializing Unity Ads in your code? If you are, just remove it.
AdMob will initialize too, and double initialization lead to this.

**Comment by rampara** [comment]
@sagar7029 the [HelloWorld sample app](https://github.com/googleads/googleads-mobile-unity/tree/master/samples/HelloWorld or the [developer docs](https://developers.google.com/admob/unity/rewarded-video) are good resources for how to implement rewarded video ads in your Unity app. 

As this issue is not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
