### ISSUE TITLE
‘GoogleMobileAds/GoogleMobileAds.h’ file not found  

### ISSUE THREAD

**Issue by kingbaggot** [googleads/googleads-mobile-unity#548]
Sorry if this seem like repetition - but I can't solve this using the processes other people have detailed in similar posts

![error](https://user-images.githubusercontent.com/4214940/31852456-df70393a-b66f-11e7-82c2-b029ff29f896.jpg)

I'm building my xcode project on my pc, then sending it to a remote mac and making the ipa there - this has worked up to now. But the googleAdMob framework doesn't seem to get bundled with the initial project, so I get this failure.

I've tried dragging the googleAdMob.framework into the framework folder from an external download but this hasn't fixed it - so am really stuck now. 

Any help massively appreciated :)

**Comment by eviltuna1911** [comment]
You need to download this and include it in your project.

https://developers.google.com/admob/ios/download

**Comment by kingbaggot** [comment]
Yup - I did download that - and dragged it into my frameworks folder - but it still gave me the same error. 

Is there a more legit way of including it ? Should I be placing it in the root folder or something first ? 

thanks for the speedy response anyway :)

**Comment by rampara** [comment]
@kingbaggot @eviltuna1911 you shouldn't have to manually download and include the GMA iOS Ads SDK in your Unity project. This plugin includes the `Play Services Resolver` library that uses Cocoapods to include declared dependencies in either a generated xcworkspace project or the standard xcode project (determined via a setting at `Assets -> Play Services Resolver -> iOS Resolver -> Settings`). I would start my taking a look at the console output when building for iOS to see if are any indications at to why the GMA iOS SDK was not included in your project.

However, as this issue is not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.

**Comment by kingbaggot** [comment]
Hi Rampara - I've been working on a pc, doing the builds there and then mailing my xcode project from there to a remote mac to build the ipa.  This has always worked fine up to now.

Is this why I'm not seeing the framework being included - because cocoapods is a mac-only thing ? When i've  set the play services resolver to make an xcworkspace project it just creates a standard xcode project with no admob sdk.

ok cheers !

**Comment by rampara** [comment]
@kingbaggot yes, you will have to perform the build on a mac for the Google Mobile Ads iOS SDK to be included in the generated Xcode project/ xcworkspace.
