### ISSUE TITLE
iOS  Only Reward Ads Don't Work! "Cannot find an ad network adapter with the name(s): GADMAdapterUnity"

### ISSUE THREAD

**Issue by alaslipknot** [googleads/googleads-mobile-unity#581]
Hi, 

Am having a very weird issue, my game Ads works perfectly on Android, and on iOS Banner and Interstitial works fine too, but whenever i call for a reward ads on iOS, i get this error : 

```
Cannot find an ad network adapter with the name(s): GADMAdapterUnity. 
Remember to link all required ad network adapters and SDKs, 
and set -ObjC in the 'Other Linker Flags' setting of your build target.
```

Am using unity 2017.1, and opened the .xcworkspace build and here is some screenshots that might be useful : 

**iOS plugin folder :** 
![image](https://user-images.githubusercontent.com/4387645/33658404-e0cd714a-da7c-11e7-8889-29f379ac335a.png)

**xCode linked libraries :**
![image](https://user-images.githubusercontent.com/4387645/33658477-1dd3632e-da7d-11e7-8d1e-79c9deb5af49.png)
 

**xCode linker flags :** 
![image](https://user-images.githubusercontent.com/4387645/33658416-ef0a3d4c-da7c-11e7-9f4f-9f5e0daba17c.png)

**xCode Modules is enable :** 
![image](https://user-images.githubusercontent.com/4387645/33658429-fbed9720-da7c-11e7-8f2d-9bc77aff7ff3.png)

Any idea what's going on please ?

Thanks

**Comment by rampara** [comment]
@alaslipknot the error you're running into is usually caused when you're not including the required mediation adapter and/or SDK in the Unity generated Xcode project. However, as this issue is not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
