### ISSUE TITLE
no fill 

### ISSUE THREAD

**Issue by gaith-thabet** [googleads/googleads-mobile-unity#589]
i had add the rewarded video ad to my game and when i use ure test id its work perfectly put when i use my id its give no fill error

**Comment by flashwade03** [comment]
@gaith-thabet HI, I think that 'no fill' error is not kind of software error. ( ex. not valid id code, network error...) That means user id doesn't have any valid advertisement data.

**Comment by gaith-thabet** [comment]
yes i see but i Waite for days and no video shown so there is a problem

**Comment by rampara** [comment]
@gaith-thabet since test ads are working without issue, it does seem like the problem lies with the ad placement id. As this issue is not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
