### ISSUE TITLE
NullReferenceException in BannerView class

### ISSUE THREAD

**Issue by araintechno** [googleads/googleads-mobile-unity#593]
Hi,
The script "AdsManager" which have code for admob integration is in "Standard Assets" folder so I moved "GoogleMobileAds" folder in to "Standard Assets" folder. But when I try to create banner ad i got this error:

NullReferenceException: Object reference not set to an instance of an object
GoogleMobileAds.Api.BannerView..ctor (System.String adUnitId, GoogleMobileAds.Api.AdSize adSize, AdPosition position) (at Assets/Standard Assets/GoogleMobileAds/Api/BannerView.cs:31)
AdsManager.requestBanner () (at Assets/Standard Assets/AdsManager.cs:69)
AdsManager.Update () (at Assets/Standard Assets/AdsManager.cs:54)

**Comment by rampara** [comment]
@araintechno the issue you're running into may be caused by [script compilation order](https://docs.unity3d.com/Manual/ScriptCompileOrderFolders.html). However, as this issue is not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
