### ISSUE TITLE
Multiple unit ID for Reward Ad

### ISSUE THREAD

**Issue by brunovals** [googleads/googleads-mobile-unity#594]
Hi, i'm new to the unity and admob

I want to ask if it's possible to load seperate ad unit ID for Rewarded Video

I have 3 unit in the console, but in the guides RewardBasedVideoAd  that we create is only to refer to it's own singleton. Which i assume if we create reference for  each unit ID in adMob it would refer to 1 same RewardBasedVideoAd, which means they shared 1 set on event handler, unlike banner and intersitial which creates new instance in initialization.

So, how can i have seperate event handler for every Rewarded Unit ID ?
Thanks

**Comment by rampara** [comment]
@brunovals currently rewarded video ads for multiple ad placements is not supported. However, this functionality in on the roadmap for a future release of the GMA SDK. However, as this issue is not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) to make feature requests.
