### ISSUE TITLE
cant make an instance to RewardeBasedVideoAd unity

### ISSUE THREAD

**Issue by morteza-master** [googleads/googleads-mobile-unity#604]
Hi.anyone can help me please.my game just closes when it runs this line of code:  rew = RewardBasedVideoAd.Instance;
i even tried this simple script to get a rewarded based video.but the result is same :(
i have imported the plugin.using latest sdk and jdk 1.8.

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;
using GoogleMobileAds;
using GoogleMobileAds.Api;
using UnityEngine.UI;

public class admanager : MonoBehaviour {
	private RewardBasedVideoAd rew;
	// Use this for initialization
	void Start () {
		rew = RewardBasedVideoAd.Instance;
		string adunitid = "ca-app-pub-3940256099942544/7325402514";
		rew.LoadAd (new AdRequest.Builder ().Build (), adunitid);
	}
	
	// Update is called once per frame
	void Update () {
		if (rew.IsLoaded ()) {
			rew.Show ();
		}
	}
}

**Comment by rampara** [comment]
@morteza-master As this issue is not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support. A stack trace of the crash would also be helpful for debugging purposes.
