### ISSUE TITLE
Ad cannot be closed even though there is close button

### ISSUE THREAD

**Issue by martin3361** [googleads/googleads-mobile-unity#650]
I'm using AdMob Unity plugin 3.7.0 in my project, with AdMob mediation configured for Admob, Unity ads, Chartboost, Vungle and AdColony.
This is the issue I experienced: even though I have enabled ad skip and the close button appeared at the top right corner, it wasn't doing anything and I had to restart the game.
I noticed that this started to happen recently.

Attached is the ad in question, I don't know which of the providers served it.
![img_2359](https://user-images.githubusercontent.com/6729011/38445188-191d07da-39fb-11e8-911e-a7cd31db80e9.PNG)

**Comment by rampara** [comment]
@martin3361 were you able to figure out which ad network serves the ads that are causing this issue fo you? The `MediationAdapterClassName()` may be helpful here. However, as this issue is not related to a bug in this plugin or a feature request, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
