### ISSUE TITLE
The latest version is giving an error about having too old a version.

### ISSUE THREAD

**Issue by penneyworth1** [googleads/googleads-mobile-unity#697]
I just loaded the newest version of the plugin into my unity project. (unity version 2018.1.0f2, XCode version 9.4.1 )
In XCode, in the logs, I see this message as the ad fails to load:

You are currently using version 7.30.0 of the SDK. Please consider updating your SDK to the most recent SDK version to get the latest features and bug fixes. The latest SDK can be downloaded from https://goo.gl/UoiJ8F. A full list of release notes is available at https://developers.google.com/admob/ios/rel-notes.
2018-06-21 16:08:49.608017-0500 helixdash[2150:668361] <Google> Cannot find an ad network adapter with the name(s): com.google.DummyAdapter. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.

What is going on?

**Comment by Mitnainartinarian** [comment]
I get the warning about updating to the latest SDK too, I think it's because the iOS-only and Unity SDKs are out of sync. It shouldn't cause any problems (at least it doesn't for me). Your second error about the ad network adapters is likely unrelated to the first one, you probably don't have any adapters set up or they're set up improperly.
