### ISSUE TITLE
iOS Compilation error

### ISSUE THREAD

**Issue by davinderkumar** [googleads/googleads-mobile-unity#712]
While compiling in Xcode 9.3, I am getting following error

In file included from /project/Assets/Plugins/iOS/GADUNativeExpressAd.m:3:
/project/Assets/Plugins/iOS/GADUNativeExpressAd.h:16:22: error: expected a type
                    (GADUTypeNativeExpressAdClientRef *)nativeExpressAdClient
                     ^
/project/Assets/Plugins/iOS/GADUNativeExpressAd.h:25:22: error: expected a type
                    (GADUTypeNativeExpressAdClientRef *)nativeExpressAdClient
                     ^
/project/Assets/Plugins/iOS/GADUNativeExpressAd.h:32:30: error: unknown type name 'GADUTypeNativeExpressAdClientRef'
@property(nonatomic, assign) GADUTypeNativeExpressAdClientRef *nativeExpressAdClient;
                             ^
/project/Assets/Plugins/iOS/GADUNativeExpressAd.m:21:22: error: expected a type
                    (GADUTypeNativeExpressAdClientRef *)nativeExpressAdClient
                     ^
/project/Assets/Plugins/iOS/GADUNativeExpressAd.m:34:22: error: expected a type
                    (GADUTypeNativeExpressAdClientRef *)nativeExpressAdClient
                     ^
/project/Assets/Plugins/iOS/GADUNativeExpressAd.m:51:22: error: expected a type
                    (GADUTypeNativeExpressAdClientRef *)nativeExpressAdClient

GADUTypeNativeExpressAdClientRef type doesn't exist in GADUTypes.h

If I add "typedef const void *GADUTypeNativeExpressAdClientRef;" in the above file then error is resolved. I'm not sure if it is correct approach.

**Comment by YashMakadia** [comment]
Even i am facing this. Did u get a solution?

**Comment by rampara** [comment]
@davinderkumar For integration issues, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.

**Comment by Tanek81** [comment]
If anyone stumbles on this issue, since the v3.13.1 in the AdMob plugin there are some obsolete classes that the Unity Package installer cannot delete (as it works only adding new files or editing existing ones), those are referencing old classes hence this error.
You can simply reinstall the plugin (deleting all the files and then reimporting the .UnityPackage ) or delete them manually, here's all the info about them: https://groups.google.com/forum/#!topic/google-admob-ads-sdk/M0NCtnTk0PY
Full credits to Andy for that post that saved me, I'll quote him in saying that "it would really help if you could provide this information with the plugin so we don't have to waste time figuring out why we have errors and what to do to resolve it".
