### ISSUE TITLE
Ad Mob Ads Not Showing 

### ISSUE THREAD

**Issue by Jbstudio425** [googleads/googleads-mobile-unity#722]
com.google.android.gms.ads.MobileAds problem is solved by :- 

> updating the version of the Google Mobile Ads SDK from 12.0.1 to 15.0.1 in Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml

`https://github.com/googleads/googleads-mobile-unity/issues/694`

**But the ads are not showing & debug is giving no errors.**

**Comment by rchallenger** [comment]
Hello, According to screenshot of Plugins folder content I can tell you that resolver didn't explode some firebase aar's wich were denedent on project's bundle or something else, that had to be pasted in plugin's manifest. See additional folders in screenshot.
![fb gad](https://user-images.githubusercontent.com/20810488/42863270-383d92fe-8a6b-11e8-94a7-83faa4500f5e.PNG)

By the way latest firebase libraries will cause manifests merge error on build. It is due to not identical "ComponentDiscoveryService" service sections in two of Firebase libraries. So they should be exploded and their manifests can be shanged by commenting these sections. Then section containig merged meta-data records can be placed in main project manifest's application section as it is written below

```xml
<application>
   <!--Firebase manifests fix-->
    <service android:name="com.google.firebase.components.ComponentDiscoveryService">
      <!--com.google.firebase.firebase-iid-->
      <meta-data android:name="com.google.firebase.components:com.google.firebase.iid.Registrar" android:value="com.google.firebase.components.ComponentRegistrar" />
      <!--com.google.firebase.firebase-measurement-connector-impl-->
      <meta-data
        android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar"
        android:value="com.google.firebase.components.ComponentRegistrar" />
    </service>
  </application>
```

**Comment by rampara** [comment]
@Jbstudio425 For integration issues, I would recommend you reach out on the [Google Mobile Ads Technical Support Forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) for further support.
