### ISSUE TITLE
Not finding com.google.unity.ads.UnityAdListener

### ISSUE THREAD

**Issue by Astirian** [googleads/googleads-mobile-unity#808]
Maybe if you stopped closing the issue without resolution this would stop cropping up? Absolute nightmare.

**Comment by Astirian** [comment]
Thank you! I've settled down now, still a bit upset I've lost so much time on it but I ended up gutting and re-importing and it works. Committing to carbonite!

**Comment by stowy** [comment]
This class is defined in a library that is included in the GoogleMobileAds unity package. If this issue is occurring, it's likely that the library is being deleted unintentionally somehow. I think re-importing the unity package should re add it. It's not downloaded by jar resolver because it's not hosted in a maven repo, it's part of the unity package.

![image](http://i63.tinypic.com/zstpxj.png)

**Comment by rchallenger** [comment]
Sure if error message in logcat says about UnityAdListener it is only ablut its absence. Though every time I get this error my plugins folder already contains this plugin. So there was something else.

**Comment by rchallenger** [comment]
[UnityAdsListener_log.txt](https://github.com/googleads/googleads-mobile-unity/files/2615554/UnityAdsListener_log.txt)

Here is a log from device, running a game with unity-plugin-library included in plugins folder.

**Comment by rchallenger** [comment]
Simple removal of GAD folder in Plugins/Android and importing it again from package solved the issue
PS: Editor was restarted once before this action
