### ISSUE TITLE
Rewarded and close callbacks called 6 times

### ISSUE THREAD

**Issue by rlee1990** [googleads/googleads-mobile-unity#867]
When I try testing the ad rewards the reward and close callbacks are called 6 times.
I have checked everything.

**Comment by UragayalaDeepika** [comment]
@rlee1990 Do you still have this issue? If yes, can you please share the complete device logs and code snippets of your implementation and can you try with our [sample apps](https://github.com/googleads/googleads-mobile-unity) and see if you are able to reproduce the issue? 

I'm closing this for now and please comment here so that we can reopen the issue for you and we will debug further.
