### ISSUE TITLE
InMobi and SmartBanners

### ISSUE THREAD

**Issue by Ruco** [googleads/googleads-mobile-unity#903]
According to this page: https://developers.google.com/admob/unity/mediation/inmobi
InMobi supports SmartBanners, although when requesting SmartBanners the InMobiAdapter reports: "Failed to request ad, AdSize is null."

**Comment by stowy** [comment]
Can you please confirm which adapter version you are using, and which device you are testing on?

**Comment by Ruco** [comment]
I am testing on a phone. The Asus Zenfone 5Z. Which has a resolution of  2246x1080. The app is in landscape. 

And the InMobiAdapter I am using is the latest version: 2.2.2
Which installs a .aar in Plugins/Android with version 7.2.7.0

**Comment by stowy** [comment]
If you try a smart banner on your phone using [this example](https://github.com/googleads/googleads-mobile-android-examples/tree/master/java/admob/BannerExample) but modifying the [banner size](https://github.com/googleads/googleads-mobile-android-examples/blob/master/java/admob/BannerExample/app/src/main/res/layout/activity_my.xml#L24) to [SMART_BANNER](https://developers.google.com/android/reference/com/google/android/gms/ads/AdSize.html#SMART_BANNER), if the ad size is only 32dp high, then there would be no ad available because InMobi doesn't [support this ad size](https://www.inmobi.com/ui/pdfs/ad-specs.pdf).

**Comment by Ruco** [comment]
Ah indeed. The lowest height available is 48dp. A pity.
It would only work in portrait or on tablets.

Thank you for clearing this up.
