### ISSUE TITLE
IPreprocessBuild' is obsolete: 'Use IPreprocessBuildWithReport instead

### ISSUE THREAD

**Issue by pozdno** [googleads/googleads-mobile-unity#953]
ManifestProcessor.cs(18,34): warning CS0618: 'IPreprocessBuild' is obsolete: 'Use IPreprocessBuildWithReport instead'
What need to do?

**Comment by ciftciMert** [comment]
I have same problem

**Comment by stowy** [comment]
IPreprocessBuildWithReport is not available on Unity 5.x, the Mobile Ads
SDK currently still supports Unity 5.x.

**Comment by Linovert** [comment]
Stowy that doesn't answer anything? I have version "2019.1.0f2" and it asks for IPreProcessBuildWithReport and then asks for a BuildReport method: .OnPreProcessBuild(BuildReport); ---> have no Idea what this is.

**Comment by Linovert** [comment]
It seems the BuildReport now stores the "target platform" and the "outputPath" https://docs.unity3d.com/ScriptReference/Build.IPreprocessBuildWithReport.OnPreprocessBuild.html

But the old OnProcessBuild() method takes in a BuildTarget and a string (the path) -> those two items should now be stored in the BuildReport object? 

https://docs.unity3d.com/ScriptReference/Build.Reporting.BuildReport.html

Can this be updated? Thanks. Or is it possible to recode it ourselves?

**Comment by Linovert** [comment]
I was able to resolve any "warnings" or "issues" with this:
1. using UnityEditor.Build.Reporting
2. public void OnPreprocessBuild(BuildReport report)

It doesn't seem that the manifest processor OnPreprocessBuild method is ever referenced/ called, neither the BuildTarget nor the path string inside the method: which can now be referenced with report.summary.platform for the target (build) platform and report.summary.outputPath for the path. Since the OnPreprocessBuild method doesn't seem to be called anywhere in the code it should be fine I hope.

**Comment by prisonbrk** [comment]
I get the same error. is the problem solved? I don't know exactly what you're doing.
